/**
 * The 78-card deck: 22 Major Arcana and 56 Minor Arcana across Wands, Cups, Swords, and Pentacles.
 *
 * GENERATED by build_cards_data.js. Do not edit this file; edit the generator and run
 * `node build_cards_data.js`.
 */

export const SUITS = [
  {
    "id": "wands",
    "name": "Wands",
    "element": "Fire",
    "domain": "Passion, Inspiration, Willpower, Action, Creativity",
    "emblem": "Staff / Flame / Salamander",
    "colors": [
      "#ff7700",
      "#ff3300",
      "#ffe600",
      "#3a0d0d"
    ]
  },
  {
    "id": "cups",
    "name": "Cups",
    "element": "Water",
    "domain": "Emotions, Love, Intuition, Relationships, Healing",
    "emblem": "Chalice / Ocean Wave / Lotus",
    "colors": [
      "#00b4d8",
      "#0077b6",
      "#90e0ef",
      "#03045e"
    ]
  },
  {
    "id": "swords",
    "name": "Swords",
    "element": "Air",
    "domain": "Intellect, Truth, Conflict, Clarity, Communication",
    "emblem": "Blade / Wind Gale / Winged Falcon",
    "colors": [
      "#b8c0ff",
      "#7209b7",
      "#4cc9f0",
      "#181829"
    ]
  },
  {
    "id": "pentacles",
    "name": "Pentacles",
    "element": "Earth",
    "domain": "Material World, Wealth, Craft, Body, Nature",
    "emblem": "Golden Talisman / Pentagram / Vine",
    "colors": [
      "#52b788",
      "#2d6a4f",
      "#e9c46a",
      "#1b4332"
    ]
  }
];

export const TAROT_DECK = [
  {
    "id": "maj_00",
    "num": 0,
    "name": "The Fool",
    "number": "0",
    "arcana": "major",
    "suit": null,
    "element": "Air",
    "ruler": "Uranus",
    "esotericTitle": "The Spirit of Aether",
    "meaningUpright": "A beginning that asks for trust rather than a plan. Step into the unknown with an open mind, and travel light.",
    "meaningReversed": "Either you are leaping without looking, or you are too afraid to take a step you need to take. Check your footing, then go.",
    "keywordsUpright": [
      "new beginnings",
      "innocence",
      "a leap of faith",
      "spontaneity",
      "potential"
    ],
    "keywordsReversed": [
      "recklessness",
      "fear of the unknown",
      "naivety",
      "hesitation",
      "carelessness"
    ]
  },
  {
    "id": "maj_01",
    "num": 1,
    "name": "The Magician",
    "number": "I",
    "arcana": "major",
    "suit": null,
    "element": "Air",
    "ruler": "Mercury",
    "esotericTitle": "The Magus of Power",
    "meaningUpright": "You have the tools and the will to make something real. Focus your attention and act.",
    "meaningReversed": "Skill without direction, or talent spent on appearances and tricks. Check whether you are deceiving others or yourself.",
    "keywordsUpright": [
      "manifestation",
      "willpower",
      "resourcefulness",
      "skill",
      "focused action"
    ],
    "keywordsReversed": [
      "manipulation",
      "untapped potential",
      "deception",
      "scattered focus",
      "illusion"
    ]
  },
  {
    "id": "maj_02",
    "num": 2,
    "name": "The High Priestess",
    "number": "II",
    "arcana": "major",
    "suit": null,
    "element": "Water",
    "ruler": "Moon",
    "esotericTitle": "Priestess of the Silver Star",
    "meaningUpright": "Trust what you already know but have not said aloud. Sit with the question instead of asking the room.",
    "meaningReversed": "You are ignoring your intuition, keeping secrets, or settling for surface answers. Listen to what you have been drowning out.",
    "keywordsUpright": [
      "intuition",
      "mystery",
      "the subconscious",
      "inner knowing",
      "stillness"
    ],
    "keywordsReversed": [
      "ignored instinct",
      "secrets",
      "superficiality",
      "detachment",
      "hidden motives"
    ]
  },
  {
    "id": "maj_03",
    "num": 3,
    "name": "The Empress",
    "number": "III",
    "arcana": "major",
    "suit": null,
    "element": "Earth",
    "ruler": "Venus",
    "esotericTitle": "Daughter of the Mighty Ones",
    "meaningUpright": "Growth, nurture, and abundance. Feed what you are growing, whether a project, a relationship, or yourself, and let it ripen.",
    "meaningReversed": "Creative block, dependence, smothering, or neglect of your own needs. Tend your own garden first.",
    "keywordsUpright": [
      "abundance",
      "fertility",
      "creativity",
      "nurturing",
      "pleasure"
    ],
    "keywordsReversed": [
      "creative block",
      "depletion",
      "smothering",
      "neglect",
      "overindulgence"
    ]
  },
  {
    "id": "maj_04",
    "num": 4,
    "name": "The Emperor",
    "number": "IV",
    "arcana": "major",
    "suit": null,
    "element": "Fire",
    "ruler": "Aries",
    "esotericTitle": "Sun of the Morning, Chief Among the Mighty",
    "meaningUpright": "Structure, authority, and discipline. Set the rules and boundaries that let the work stand up.",
    "meaningReversed": "Control has become rigid or tyrannical, or there is no structure at all. Ask whether firmness has become stubbornness.",
    "keywordsUpright": [
      "authority",
      "structure",
      "stability",
      "discipline",
      "leadership"
    ],
    "keywordsReversed": [
      "tyranny",
      "rigidity",
      "chaos",
      "micromanagement",
      "loss of control"
    ]
  },
  {
    "id": "maj_05",
    "num": 5,
    "name": "The Hierophant",
    "number": "V",
    "arcana": "major",
    "suit": null,
    "element": "Earth",
    "ruler": "Taurus",
    "esotericTitle": "Magus of the Eternal Gods",
    "meaningUpright": "Tradition, teaching, and shared belief. Learn the way this has been done before you decide to do it differently.",
    "meaningReversed": "Dogma, hypocrisy, or rebellion against rules that no longer fit. Question the form, but do not reject it out of spite.",
    "keywordsUpright": [
      "tradition",
      "mentorship",
      "wisdom",
      "institutions",
      "shared belief"
    ],
    "keywordsReversed": [
      "dogma",
      "rebellion",
      "unconventional paths",
      "hypocrisy",
      "conformity"
    ]
  },
  {
    "id": "maj_06",
    "num": 6,
    "name": "The Lovers",
    "number": "VI",
    "arcana": "major",
    "suit": null,
    "element": "Air",
    "ruler": "Gemini",
    "esotericTitle": "The Children of the Voice Divine",
    "meaningUpright": "A union, or a choice about what you value. Choose what you can live with, not only what you feel.",
    "meaningReversed": "Misaligned values, a divided heart, or a choice you keep refusing to make. You cannot walk two roads at once.",
    "keywordsUpright": [
      "union",
      "harmony",
      "shared values",
      "connection",
      "choice"
    ],
    "keywordsReversed": [
      "disharmony",
      "misalignment",
      "conflict",
      "indecision",
      "broken bonds"
    ]
  },
  {
    "id": "maj_07",
    "num": 7,
    "name": "The Chariot",
    "number": "VII",
    "arcana": "major",
    "suit": null,
    "element": "Water",
    "ruler": "Cancer",
    "esotericTitle": "Child of the Powers of the Waters",
    "meaningUpright": "Victory through will and focus. Hold the opposing pulls together and steer.",
    "meaningReversed": "Loss of direction, aggression, or force without a goal. Fix what is steering before you push harder.",
    "keywordsUpright": [
      "determination",
      "willpower",
      "victory",
      "control",
      "focus"
    ],
    "keywordsReversed": [
      "loss of control",
      "aggression",
      "obstacles",
      "aimlessness",
      "a hard stop"
    ]
  },
  {
    "id": "maj_08",
    "num": 8,
    "name": "Strength",
    "number": "VIII",
    "arcana": "major",
    "suit": null,
    "element": "Fire",
    "ruler": "Leo",
    "esotericTitle": "Daughter of the Flaming Sword",
    "meaningUpright": "Courage that does not need to shout. Meet what is fierce in you or around you with patience and a steady hand.",
    "meaningReversed": "Self-doubt, temper, or fear you are trying to force down. Real strength is quiet; find it again.",
    "keywordsUpright": [
      "inner strength",
      "compassion",
      "patience",
      "courage",
      "calm"
    ],
    "keywordsReversed": [
      "self-doubt",
      "aggression",
      "impatience",
      "weakness",
      "burnout"
    ]
  },
  {
    "id": "maj_09",
    "num": 9,
    "name": "The Hermit",
    "number": "IX",
    "arcana": "major",
    "suit": null,
    "element": "Earth",
    "ruler": "Virgo",
    "esotericTitle": "Magus of the Voice of Light",
    "meaningUpright": "Solitude and reflection. Step away from the noise to find your own answer.",
    "meaningReversed": "Isolation, loneliness, or refusing the quiet because it would tell you something. Come back far enough to be reached, or go far enough to hear yourself.",
    "keywordsUpright": [
      "introspection",
      "solitude",
      "guidance",
      "searching",
      "discernment"
    ],
    "keywordsReversed": [
      "isolation",
      "loneliness",
      "withdrawal",
      "paranoia",
      "feeling lost"
    ]
  },
  {
    "id": "maj_10",
    "num": 10,
    "name": "Wheel of Fortune",
    "number": "X",
    "arcana": "major",
    "suit": null,
    "element": "Fire",
    "ruler": "Jupiter",
    "esotericTitle": "Lord of the Forces of Life",
    "meaningUpright": "A turn of fortune, a change of season. Something stuck is moving; ride it rather than resisting it.",
    "meaningReversed": "Bad luck, resistance to change, or a cycle you keep repeating. You cannot wind the wheel back; work with where it is.",
    "keywordsUpright": [
      "cycles",
      "change",
      "good fortune",
      "turning points",
      "luck"
    ],
    "keywordsReversed": [
      "misfortune",
      "resistance to change",
      "stagnation",
      "bad timing",
      "disruption"
    ]
  },
  {
    "id": "maj_11",
    "num": 11,
    "name": "Justice",
    "number": "XI",
    "arcana": "major",
    "suit": null,
    "element": "Air",
    "ruler": "Libra",
    "esotericTitle": "Daughter of the Lords of Truth",
    "meaningUpright": "Cause and effect, fairness, and accountability. What was done will be weighed; be honest about your part.",
    "meaningReversed": "Unfairness, bias, dishonesty, or avoiding responsibility. Check whose thumb is on the scale.",
    "keywordsUpright": [
      "truth",
      "fairness",
      "cause and effect",
      "integrity",
      "accountability"
    ],
    "keywordsReversed": [
      "injustice",
      "bias",
      "dishonesty",
      "evasion",
      "conflict"
    ]
  },
  {
    "id": "maj_12",
    "num": 12,
    "name": "The Hanged Man",
    "number": "XII",
    "arcana": "major",
    "suit": null,
    "element": "Water",
    "ruler": "Neptune",
    "esotericTitle": "Spirit of the Mighty Waters",
    "meaningUpright": "A pause, a surrender, a new angle. Stop forcing the outcome and let the view change.",
    "meaningReversed": "Stalling, martyrdom, or resistance disguised as patience. Letting go is not the same as doing nothing.",
    "keywordsUpright": [
      "surrender",
      "new perspective",
      "pause",
      "letting go",
      "suspension"
    ],
    "keywordsReversed": [
      "martyrdom",
      "stagnation",
      "resistance",
      "indecision",
      "delay"
    ]
  },
  {
    "id": "maj_13",
    "num": 13,
    "name": "Death",
    "number": "XIII",
    "arcana": "major",
    "suit": null,
    "element": "Water",
    "ruler": "Scorpio",
    "esotericTitle": "Child of the Great Transformers",
    "meaningUpright": "An ending that makes room. Let what is finished be finished so something else can begin.",
    "meaningReversed": "Fear of change, clinging to what is already over, or an ending dragged out past its time. Let it end.",
    "keywordsUpright": [
      "transformation",
      "endings",
      "release",
      "transition",
      "renewal"
    ],
    "keywordsReversed": [
      "clinging to the past",
      "fear of change",
      "stagnation",
      "prolonged endings",
      "resistance"
    ]
  },
  {
    "id": "maj_14",
    "num": 14,
    "name": "Temperance",
    "number": "XIV",
    "arcana": "major",
    "suit": null,
    "element": "Fire",
    "ruler": "Sagittarius",
    "esotericTitle": "Daughter of the Reconcilers",
    "meaningUpright": "Balance, patience, and moderation. Blend the opposites rather than choosing one.",
    "meaningReversed": "Excess, imbalance, or forcing together things that do not mix. Restore the middle before you continue.",
    "keywordsUpright": [
      "balance",
      "moderation",
      "patience",
      "harmony",
      "integration"
    ],
    "keywordsReversed": [
      "imbalance",
      "excess",
      "discord",
      "impatience",
      "extremes"
    ]
  },
  {
    "id": "maj_15",
    "num": 15,
    "name": "The Devil",
    "number": "XV",
    "arcana": "major",
    "suit": null,
    "element": "Earth",
    "ruler": "Capricorn",
    "esotericTitle": "Lord of the Gates of Matter",
    "meaningUpright": "Attachment, compulsion, and the feeling of being trapped. The chains are looser than they look.",
    "meaningReversed": "Breaking free of a habit, a bond, or a belief that held you. Seeing the chain is the first step; lifting it is the second.",
    "keywordsUpright": [
      "attachment",
      "materialism",
      "compulsion",
      "feeling trapped",
      "temptation"
    ],
    "keywordsReversed": [
      "liberation",
      "breaking free",
      "awakening",
      "reclaiming power",
      "release"
    ]
  },
  {
    "id": "maj_16",
    "num": 16,
    "name": "The Tower",
    "number": "XVI",
    "arcana": "major",
    "suit": null,
    "element": "Fire",
    "ruler": "Mars",
    "esotericTitle": "Lord of the Hosts of the Mighty",
    "meaningUpright": "Sudden upheaval that brings down what was built on a false footing. It is painful, and it clears the ground.",
    "meaningReversed": "Disaster averted, or disaster denied: the structure is cracking and you are not looking. Face the fault before it faces you.",
    "keywordsUpright": [
      "upheaval",
      "revelation",
      "collapse",
      "breakthrough",
      "hard truth"
    ],
    "keywordsReversed": [
      "disaster averted",
      "denial",
      "fear of change",
      "delaying the inevitable",
      "a slow collapse"
    ]
  },
  {
    "id": "maj_17",
    "num": 17,
    "name": "The Star",
    "number": "XVII",
    "arcana": "major",
    "suit": null,
    "element": "Air",
    "ruler": "Aquarius",
    "esotericTitle": "Daughter of the Firmament",
    "meaningUpright": "Hope, healing, and renewed faith after a hard stretch. Look up; the way is clearer than it was.",
    "meaningReversed": "Despair, cynicism, or lost faith in your own gifts. The stars have not gone; you have stopped looking for them.",
    "keywordsUpright": [
      "hope",
      "inspiration",
      "serenity",
      "healing",
      "faith"
    ],
    "keywordsReversed": [
      "despair",
      "disillusionment",
      "cynicism",
      "lost faith",
      "discouragement"
    ]
  },
  {
    "id": "maj_18",
    "num": 18,
    "name": "The Moon",
    "number": "XVIII",
    "arcana": "major",
    "suit": null,
    "element": "Water",
    "ruler": "Pisces",
    "esotericTitle": "Ruler of Flux and Reflux",
    "meaningUpright": "Illusion, fear, and the pull of the subconscious. Not everything is what it seems; move slowly and trust your instincts.",
    "meaningReversed": "The fog is lifting and the fears are shrinking. What frightened you is smaller in daylight.",
    "keywordsUpright": [
      "illusion",
      "intuition",
      "fear",
      "dreams",
      "uncertainty"
    ],
    "keywordsReversed": [
      "clarity",
      "truth revealed",
      "fear released",
      "understanding",
      "calm"
    ]
  },
  {
    "id": "maj_19",
    "num": 19,
    "name": "The Sun",
    "number": "XIX",
    "arcana": "major",
    "suit": null,
    "element": "Fire",
    "ruler": "Sun",
    "esotericTitle": "Lord of the Fire of the World",
    "meaningUpright": "Joy, vitality, and success in plain sight. Enjoy a good day for what it is.",
    "meaningReversed": "A clouded or muted joy, unrealistic optimism, or burnout from too much of a good thing. The sun is still there behind the mist.",
    "keywordsUpright": [
      "joy",
      "vitality",
      "success",
      "clarity",
      "warmth"
    ],
    "keywordsReversed": [
      "clouded joy",
      "muted enthusiasm",
      "unrealistic expectations",
      "burnout",
      "delay"
    ]
  },
  {
    "id": "maj_20",
    "num": 20,
    "name": "Judgement",
    "number": "XX",
    "arcana": "major",
    "suit": null,
    "element": "Fire",
    "ruler": "Pluto",
    "esotericTitle": "The Spirit of the Primal Fire",
    "meaningUpright": "A reckoning and a calling. Take stock of what you have done and answer the summons to change.",
    "meaningReversed": "Harsh self-judgment, ignoring the call, or guilt that keeps you from moving. Forgive what needs forgiving and get up.",
    "keywordsUpright": [
      "reckoning",
      "awakening",
      "a calling",
      "forgiveness",
      "renewal"
    ],
    "keywordsReversed": [
      "self-doubt",
      "harsh judgment",
      "ignoring the call",
      "guilt",
      "hesitation"
    ]
  },
  {
    "id": "maj_21",
    "num": 21,
    "name": "The World",
    "number": "XXI",
    "arcana": "major",
    "suit": null,
    "element": "Earth",
    "ruler": "Saturn",
    "esotericTitle": "The Great One of the Night of Time",
    "meaningUpright": "Completion and wholeness. A cycle has finished; celebrate it before the next one begins.",
    "meaningReversed": "Unfinished business, shortcuts, or a delay at the final step. Finish the last mile.",
    "keywordsUpright": [
      "completion",
      "wholeness",
      "achievement",
      "integration",
      "fulfillment"
    ],
    "keywordsReversed": [
      "incompleteness",
      "unfinished business",
      "delay",
      "emptiness",
      "shortcuts"
    ]
  },
  {
    "id": "wands_ace",
    "num": 1,
    "name": "Ace of Wands",
    "number": "A",
    "rank": "ace",
    "rankLabel": "Ace",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Root of the Powers of Fire",
    "meaningUpright": "A new idea, project, or desire has real energy behind it. Start while the spark is hot rather than waiting to feel ready.",
    "meaningReversed": "You want to begin but cannot find the push, or the push keeps getting spent on the wrong thing. Wait for the real spark, then act on it quickly.",
    "keywordsUpright": [
      "inspiration",
      "a creative spark",
      "potential",
      "initiative"
    ],
    "keywordsReversed": [
      "hesitation",
      "burnout",
      "low energy",
      "creative block"
    ]
  },
  {
    "id": "wands_2",
    "num": 2,
    "name": "Two of Wands",
    "number": "II",
    "rank": "2",
    "rankLabel": "Two",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Dominion",
    "meaningUpright": "You have done well enough to want more, and you are weighing where to go next. Plan the longer route and commit to one direction.",
    "meaningReversed": "You are afraid to leave what you know, so the plan stays a plan. Either go, or admit you have chosen to stay.",
    "keywordsUpright": [
      "planning",
      "ambition",
      "a decision",
      "the long view"
    ],
    "keywordsReversed": [
      "fear of the unknown",
      "playing it safe",
      "bad timing",
      "indecision"
    ]
  },
  {
    "id": "wands_3",
    "num": 3,
    "name": "Three of Wands",
    "number": "III",
    "rank": "3",
    "rankLabel": "Three",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Established Strength",
    "meaningUpright": "What you set in motion is starting to come back to you. Expect progress, news from a distance, and room to expand.",
    "meaningReversed": "Results are slower than you expected and the plan looks shakier than it did. Check what is actually in motion before you assume it has failed.",
    "keywordsUpright": [
      "expansion",
      "foresight",
      "progress",
      "first results"
    ],
    "keywordsReversed": [
      "delays",
      "frustration",
      "obstacles",
      "an unrealized plan"
    ]
  },
  {
    "id": "wands_4",
    "num": 4,
    "name": "Four of Wands",
    "number": "IV",
    "rank": "4",
    "rankLabel": "Four",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Perfected Work",
    "meaningUpright": "Something is worth celebrating: a homecoming, a milestone, a place that finally feels settled. Enjoy it with the people who helped.",
    "meaningReversed": "Home, or the group you count on, feels unsettled, or a celebration has tension under it. Repair the foundation before you plan the party.",
    "keywordsUpright": [
      "homecoming",
      "celebration",
      "community",
      "stability"
    ],
    "keywordsReversed": [
      "instability",
      "family tension",
      "a delayed return",
      "insecurity"
    ]
  },
  {
    "id": "wands_5",
    "num": 5,
    "name": "Five of Wands",
    "number": "V",
    "rank": "5",
    "rankLabel": "Five",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Strife",
    "meaningUpright": "Competing wants, voices, or egos are pulling in different directions. Treat the friction as a workout rather than a war, and look for the useful idea in the noise.",
    "meaningReversed": "The squabbling has either worn everyone out or is about to turn genuinely hostile. Step back from a fight that no longer has a point.",
    "keywordsUpright": [
      "competition",
      "disagreement",
      "friction",
      "clashing egos"
    ],
    "keywordsReversed": [
      "petty bickering",
      "exhaustion",
      "avoiding conflict",
      "finding agreement"
    ]
  },
  {
    "id": "wands_6",
    "num": 6,
    "name": "Six of Wands",
    "number": "VI",
    "rank": "6",
    "rankLabel": "Six",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Victory",
    "meaningUpright": "You have earned a win and other people can see it. Accept the recognition without apologizing for it.",
    "meaningReversed": "Recognition is late, missing, or hollow, and pride may be covering a private disappointment. Measure the win by what you did, not by the applause.",
    "keywordsUpright": [
      "victory",
      "recognition",
      "confidence",
      "pride"
    ],
    "keywordsReversed": [
      "inflated ego",
      "a fall from favor",
      "hollow praise",
      "lost standing"
    ]
  },
  {
    "id": "wands_7",
    "num": 7,
    "name": "Seven of Wands",
    "number": "VII",
    "rank": "7",
    "rankLabel": "Seven",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Valour",
    "meaningUpright": "You hold a position others are challenging, and you are right to defend it. Stand your ground, but pick the battles that matter.",
    "meaningReversed": "Defending everything has exhausted you, and some of what you are guarding is not worth the fight. Lower the guard where you can and rest.",
    "keywordsUpright": [
      "standing your ground",
      "conviction",
      "defense",
      "courage under pressure"
    ],
    "keywordsReversed": [
      "feeling overwhelmed",
      "exhaustion",
      "giving in",
      "defensiveness"
    ]
  },
  {
    "id": "wands_8",
    "num": 8,
    "name": "Eight of Wands",
    "number": "VIII",
    "rank": "8",
    "rankLabel": "Eight",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Swiftness",
    "meaningUpright": "Things are moving fast and in your favor. Expect quick news and quick progress, and keep your attention on the direction rather than the speed.",
    "meaningReversed": "Delays, crossed messages, and haste are scrambling what should have been quick. Slow down enough to read what is actually in front of you.",
    "keywordsUpright": [
      "momentum",
      "quick news",
      "fast progress",
      "alignment"
    ],
    "keywordsReversed": [
      "delays",
      "haste",
      "crossed messages",
      "frustration"
    ]
  },
  {
    "id": "wands_9",
    "num": 9,
    "name": "Nine of Wands",
    "number": "IX",
    "rank": "9",
    "rankLabel": "Nine",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Great Strength",
    "meaningUpright": "You are tired and bruised but still standing, and the end is closer than it feels. Hold the line a little longer.",
    "meaningReversed": "You are braced for a blow that may never come, and the vigilance is costing more than the danger would. Let the guard down where it is safe to.",
    "keywordsUpright": [
      "resilience",
      "persistence",
      "a last stand",
      "endurance"
    ],
    "keywordsReversed": [
      "exhaustion",
      "hypervigilance",
      "paranoia",
      "walls too high"
    ]
  },
  {
    "id": "wands_10",
    "num": 10,
    "name": "Ten of Wands",
    "number": "X",
    "rank": "10",
    "rankLabel": "Ten",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of Oppression",
    "meaningUpright": "You are carrying more than your share, and you are close to the finish. Set something down, or ask for help before you drop all of it.",
    "meaningReversed": "You are either buckling under the load or finally putting some of it down. Delegate what you can and stop treating exhaustion as a virtue.",
    "keywordsUpright": [
      "burden",
      "overcommitment",
      "responsibility",
      "nearly there"
    ],
    "keywordsReversed": [
      "delegation",
      "collapse",
      "dropping the load",
      "refusing martyrdom"
    ]
  },
  {
    "id": "wands_page",
    "num": 11,
    "name": "Page of Wands",
    "number": "P",
    "rank": "page",
    "rankLabel": "Page",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Princess of the Shining Flame",
    "meaningUpright": "A new enthusiasm wants your attention: a message, a hobby, a bold idea. Follow it with curiosity and see where it points.",
    "meaningReversed": "Enthusiasm is scattered or all talk, and nothing is being finished. Pick one spark and give it a week of real attention.",
    "keywordsUpright": [
      "enthusiasm",
      "curiosity",
      "a new idea",
      "adventure"
    ],
    "keywordsReversed": [
      "flightiness",
      "procrastination",
      "empty promises",
      "impatience"
    ]
  },
  {
    "id": "wands_knight",
    "num": 12,
    "name": "Knight of Wands",
    "number": "Kn",
    "rank": "knight",
    "rankLabel": "Knight",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of the Flame and Lightning",
    "meaningUpright": "Act boldly and move fast; this is a card of charge, passion, and daring. Just check the direction before you floor it.",
    "meaningReversed": "Recklessness, temper, or impatience is leaving wreckage behind. Slow down and ask what you are actually chasing.",
    "keywordsUpright": [
      "boldness",
      "passion",
      "action",
      "energy"
    ],
    "keywordsReversed": [
      "recklessness",
      "temper",
      "impulsiveness",
      "burnout"
    ]
  },
  {
    "id": "wands_queen",
    "num": 13,
    "name": "Queen of Wands",
    "number": "Q",
    "rank": "queen",
    "rankLabel": "Queen",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Queen of the Thrones of Flame",
    "meaningUpright": "Confidence, warmth, and energy that draws people in. Lead by being yourself and lift others as you go.",
    "meaningReversed": "The warmth has turned demanding or jealous, or confidence has slipped into insecurity. Ask for what you need instead of performing that you need nothing.",
    "keywordsUpright": [
      "confidence",
      "warmth",
      "charisma",
      "leadership"
    ],
    "keywordsReversed": [
      "jealousy",
      "drama",
      "insecurity",
      "demanding attention"
    ]
  },
  {
    "id": "wands_king",
    "num": 14,
    "name": "King of Wands",
    "number": "K",
    "rank": "king",
    "rankLabel": "King",
    "arcana": "minor",
    "suit": "wands",
    "suitName": "Wands",
    "element": "Fire",
    "ruler": null,
    "esotericTitle": "Lord of the Flame and Lightning",
    "meaningUpright": "Lead with vision and nerve; you can see the whole picture and inspire others to build it. Delegate the details and keep your eye on the direction.",
    "meaningReversed": "Vision has tipped into impatience, arrogance, or impossible demands on other people. Ask for less than everything and listen more than you speak.",
    "keywordsUpright": [
      "vision",
      "leadership",
      "boldness",
      "inspiration"
    ],
    "keywordsReversed": [
      "arrogance",
      "impossible expectations",
      "temper",
      "domineering"
    ]
  },
  {
    "id": "cups_ace",
    "num": 1,
    "name": "Ace of Cups",
    "number": "A",
    "rank": "ace",
    "rankLabel": "Ace",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Root of the Powers of Water",
    "meaningUpright": "Feeling opens up: new love, compassion, a creative or spiritual beginning. Let yourself receive it rather than analyzing it.",
    "meaningReversed": "Feelings are blocked, drained, or being held back out of fear. Notice what you are refusing to feel, and why.",
    "keywordsUpright": [
      "love",
      "compassion",
      "emotional opening",
      "new feeling"
    ],
    "keywordsReversed": [
      "emotional drain",
      "blocked feelings",
      "fear of vulnerability",
      "heartache"
    ]
  },
  {
    "id": "cups_2",
    "num": 2,
    "name": "Two of Cups",
    "number": "II",
    "rank": "2",
    "rankLabel": "Two",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Love",
    "meaningUpright": "A real connection, met halfway: partnership, attraction, or mutual respect. Give and receive in equal measure.",
    "meaningReversed": "The balance in a relationship is off, and one side is giving or withholding too much. Name the imbalance before it becomes distance.",
    "keywordsUpright": [
      "partnership",
      "mutual respect",
      "harmony",
      "connection"
    ],
    "keywordsReversed": [
      "imbalance",
      "broken trust",
      "codependency",
      "disconnection"
    ]
  },
  {
    "id": "cups_3",
    "num": 3,
    "name": "Three of Cups",
    "number": "III",
    "rank": "3",
    "rankLabel": "Three",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Abundance",
    "meaningUpright": "Friends, celebration, and shared joy. Gather the people you love and mark the moment.",
    "meaningReversed": "A circle of friends feels strained, exclusive, or exhausted by too much of a good thing. Step back from gossip and overindulgence.",
    "keywordsUpright": [
      "celebration",
      "community",
      "friendship",
      "shared joy"
    ],
    "keywordsReversed": [
      "overindulgence",
      "gossip",
      "exclusion",
      "shallow friendship"
    ]
  },
  {
    "id": "cups_4",
    "num": 4,
    "name": "Four of Cups",
    "number": "IV",
    "rank": "4",
    "rankLabel": "Four",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Blended Pleasure",
    "meaningUpright": "You are bored or discontented, and an offer is sitting in front of you unnoticed. Look up from what is wrong and see what is being offered.",
    "meaningReversed": "You are coming out of a slump and ready to engage again. Take the opportunity you overlooked before.",
    "keywordsUpright": [
      "apathy",
      "contemplation",
      "discontent",
      "a missed offer"
    ],
    "keywordsReversed": [
      "renewed interest",
      "seizing an opportunity",
      "waking up",
      "gratitude"
    ]
  },
  {
    "id": "cups_5",
    "num": 5,
    "name": "Five of Cups",
    "number": "V",
    "rank": "5",
    "rankLabel": "Five",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Loss in Pleasure",
    "meaningUpright": "Grief and regret over what has been lost. Mourn it, and then notice what is still standing behind you.",
    "meaningReversed": "You are starting to accept the loss and see what remains. Recovery and forgiveness are within reach.",
    "keywordsUpright": [
      "grief",
      "regret",
      "loss",
      "disappointment"
    ],
    "keywordsReversed": [
      "acceptance",
      "recovery",
      "hope",
      "gratitude for what remains"
    ]
  },
  {
    "id": "cups_6",
    "num": 6,
    "name": "Six of Cups",
    "number": "VI",
    "rank": "6",
    "rankLabel": "Six",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Pleasure",
    "meaningUpright": "Nostalgia, old friends, and the comfort of childhood memories. Let the past be sweet without moving back into it.",
    "meaningReversed": "You are living in the past or refusing to grow up. Visit the memory and then come back to the present.",
    "keywordsUpright": [
      "nostalgia",
      "memories",
      "innocence",
      "kindness"
    ],
    "keywordsReversed": [
      "stuck in the past",
      "immaturity",
      "rose-tinted memory",
      "moving on"
    ]
  },
  {
    "id": "cups_7",
    "num": 7,
    "name": "Seven of Cups",
    "number": "VII",
    "rank": "7",
    "rankLabel": "Seven",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Illusionary Success",
    "meaningUpright": "Too many options, and some of them are only fantasies. Look hard at what each one really offers before you choose.",
    "meaningReversed": "The daydreams are clearing and one real choice is coming into focus. Commit to it.",
    "keywordsUpright": [
      "daydreams",
      "too many options",
      "fantasy",
      "wishful thinking"
    ],
    "keywordsReversed": [
      "clarity",
      "a clear choice",
      "realism",
      "decisive action"
    ]
  },
  {
    "id": "cups_8",
    "num": 8,
    "name": "Eight of Cups",
    "number": "VIII",
    "rank": "8",
    "rankLabel": "Eight",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Abandoned Success",
    "meaningUpright": "You are leaving something that no longer satisfies you, even though it still looks fine from outside. The walk away is the point.",
    "meaningReversed": "You are afraid to leave, or drifting without deciding, and you keep returning to what does not feed you. Either go or recommit.",
    "keywordsUpright": [
      "walking away",
      "searching for meaning",
      "a departure",
      "letting go"
    ],
    "keywordsReversed": [
      "fear of leaving",
      "drifting",
      "clinging to comfort",
      "avoidance"
    ]
  },
  {
    "id": "cups_9",
    "num": 9,
    "name": "Nine of Cups",
    "number": "IX",
    "rank": "9",
    "rankLabel": "Nine",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Material Happiness",
    "meaningUpright": "Contentment and wishes fulfilled. Enjoy what you have built without hunting for the catch.",
    "meaningReversed": "The satisfaction is shallow or smug, and something underneath still feels empty. Ask whether you are full or just comfortable.",
    "keywordsUpright": [
      "wishes fulfilled",
      "satisfaction",
      "contentment",
      "pleasure"
    ],
    "keywordsReversed": [
      "smugness",
      "greed",
      "shallow comfort",
      "emptiness"
    ]
  },
  {
    "id": "cups_10",
    "num": 10,
    "name": "Ten of Cups",
    "number": "X",
    "rank": "10",
    "rankLabel": "Ten",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of Perfected Success",
    "meaningUpright": "Lasting happiness in family, home, and community. This is the harmony the other cards were working toward.",
    "meaningReversed": "Home life is strained, or the picture of perfection does not match what is going on inside it. Fix what is really happening rather than the image.",
    "keywordsUpright": [
      "lasting happiness",
      "family harmony",
      "community",
      "fulfillment"
    ],
    "keywordsReversed": [
      "domestic discord",
      "a shattered ideal",
      "alienation",
      "false harmony"
    ]
  },
  {
    "id": "cups_page",
    "num": 11,
    "name": "Page of Cups",
    "number": "P",
    "rank": "page",
    "rankLabel": "Page",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Princess of the Waters",
    "meaningUpright": "An intuitive message, a creative impulse, or a tender surprise. Stay open and curious about what you feel.",
    "meaningReversed": "Emotional immaturity, moodiness, or escape into fantasy. Feelings are information, not verdicts.",
    "keywordsUpright": [
      "intuition",
      "creativity",
      "tenderness",
      "a surprise"
    ],
    "keywordsReversed": [
      "fragility",
      "mood swings",
      "escapism",
      "drama"
    ]
  },
  {
    "id": "cups_knight",
    "num": 12,
    "name": "Knight of Cups",
    "number": "Kn",
    "rank": "knight",
    "rankLabel": "Knight",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Lord of the Waves and Waters",
    "meaningUpright": "A romantic offer, an idealistic quest, or a charming messenger. Follow the heart, but check that there is a plan behind the charm.",
    "meaningReversed": "Charm without follow-through, moodiness, or manipulation dressed up as romance. Judge by actions, not promises.",
    "keywordsUpright": [
      "romance",
      "idealism",
      "charm",
      "an invitation"
    ],
    "keywordsReversed": [
      "fickleness",
      "manipulation",
      "disappointment",
      "moodiness"
    ]
  },
  {
    "id": "cups_queen",
    "num": 13,
    "name": "Queen of Cups",
    "number": "Q",
    "rank": "queen",
    "rankLabel": "Queen",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Queen of the Thrones of Water",
    "meaningUpright": "Deep empathy and emotional wisdom. Listen to your intuition and offer compassion without losing yourself in other people's feelings.",
    "meaningReversed": "Absorbing everyone's emotions has left you drained or codependent. Tend your own feelings before you carry anyone else's.",
    "keywordsUpright": [
      "empathy",
      "intuition",
      "compassion",
      "emotional wisdom"
    ],
    "keywordsReversed": [
      "codependency",
      "emotional manipulation",
      "martyrdom",
      "feeling overwhelmed"
    ]
  },
  {
    "id": "cups_king",
    "num": 14,
    "name": "King of Cups",
    "number": "K",
    "rank": "king",
    "rankLabel": "King",
    "arcana": "minor",
    "suit": "cups",
    "suitName": "Cups",
    "element": "Water",
    "ruler": null,
    "esotericTitle": "Prince of the Chariot of the Waters",
    "meaningUpright": "Calm in emotional storms: compassion balanced with control. Lead with steadiness and help others find theirs.",
    "meaningReversed": "Feelings are being suppressed, manipulated, or vented sideways. Say what you feel directly instead of managing everyone around it.",
    "keywordsUpright": [
      "emotional balance",
      "compassion",
      "calm",
      "wisdom"
    ],
    "keywordsReversed": [
      "volatility",
      "cold withdrawal",
      "passive aggression",
      "deceit"
    ]
  },
  {
    "id": "swords_ace",
    "num": 1,
    "name": "Ace of Swords",
    "number": "A",
    "rank": "ace",
    "rankLabel": "Ace",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Root of the Powers of Air",
    "meaningUpright": "A breakthrough in clarity: the truth is suddenly plain. Act on what you now see.",
    "meaningReversed": "Thinking is clouded, or the truth is being used as a weapon. Wait for clarity before you cut.",
    "keywordsUpright": [
      "clarity",
      "truth",
      "breakthrough",
      "a decision"
    ],
    "keywordsReversed": [
      "confusion",
      "hostility",
      "miscommunication",
      "harsh judgment"
    ]
  },
  {
    "id": "swords_2",
    "num": 2,
    "name": "Two of Swords",
    "number": "II",
    "rank": "2",
    "rankLabel": "Two",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Peace Restored",
    "meaningUpright": "A stalemate between two choices, and you are avoiding looking at either. Decide, even without certainty.",
    "meaningReversed": "The information is overwhelming, or a truth is forcing its way through a denial. The decision is about to make itself if you do not.",
    "keywordsUpright": [
      "stalemate",
      "a hard choice",
      "truce",
      "deliberation"
    ],
    "keywordsReversed": [
      "avoidance",
      "overload",
      "a false truce",
      "indecision exposed"
    ]
  },
  {
    "id": "swords_3",
    "num": 3,
    "name": "Three of Swords",
    "number": "III",
    "rank": "3",
    "rankLabel": "Three",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Sorrow",
    "meaningUpright": "Heartbreak, painful truth, or grief that cuts clean. Feel it fully; it heals cleaner for being felt.",
    "meaningReversed": "You are releasing old pain, forgiving, or finally healing a wound you have carried. Let it close.",
    "keywordsUpright": [
      "heartbreak",
      "grief",
      "painful truth",
      "release"
    ],
    "keywordsReversed": [
      "healing",
      "forgiveness",
      "moving on",
      "reconciliation"
    ]
  },
  {
    "id": "swords_4",
    "num": 4,
    "name": "Four of Swords",
    "number": "IV",
    "rank": "4",
    "rankLabel": "Four",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Rest from Strife",
    "meaningUpright": "Rest, retreat, and recovery. Step back from the fight to recuperate.",
    "meaningReversed": "Rest has gone on too long, or you are refusing the rest you need. Either get back up or let yourself stop.",
    "keywordsUpright": [
      "rest",
      "retreat",
      "recovery",
      "quiet"
    ],
    "keywordsReversed": [
      "burnout",
      "restlessness",
      "forced withdrawal",
      "returning too soon"
    ]
  },
  {
    "id": "swords_5",
    "num": 5,
    "name": "Five of Swords",
    "number": "V",
    "rank": "5",
    "rankLabel": "Five",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Defeat",
    "meaningUpright": "A win that costs more than it is worth: conflict, hostility, and a hollow victory. Ask whether being right was worth what it cost.",
    "meaningReversed": "You are ready to walk away from a pointless fight, or to make amends after one. Take the exit.",
    "keywordsUpright": [
      "a hollow victory",
      "conflict",
      "hostility",
      "winning at a cost"
    ],
    "keywordsReversed": [
      "forgiveness",
      "walking away",
      "healing resentment",
      "remorse"
    ]
  },
  {
    "id": "swords_6",
    "num": 6,
    "name": "Six of Swords",
    "number": "VI",
    "rank": "6",
    "rankLabel": "Six",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Earned Success",
    "meaningUpright": "A transition from rough water to calmer. Progress is quiet, but it is real; keep going.",
    "meaningReversed": "You are stuck in transition, carrying baggage you cannot leave behind, or heading back into the storm. Commit to the far shore.",
    "keywordsUpright": [
      "transition",
      "calmer water",
      "relief",
      "moving on"
    ],
    "keywordsReversed": [
      "baggage",
      "relapse",
      "a delayed move",
      "resistance to change"
    ]
  },
  {
    "id": "swords_7",
    "num": 7,
    "name": "Seven of Swords",
    "number": "VII",
    "rank": "7",
    "rankLabel": "Seven",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Unstable Effort",
    "meaningUpright": "Strategy, stealth, or getting away with something. Cleverness has its place, but check whether you are deceiving others or yourself.",
    "meaningReversed": "Deception is being exposed, or your conscience is catching up with you. Come clean before you are caught out.",
    "keywordsUpright": [
      "strategy",
      "stealth",
      "cunning",
      "discretion"
    ],
    "keywordsReversed": [
      "getting caught",
      "exposed deception",
      "conscience",
      "confession"
    ]
  },
  {
    "id": "swords_8",
    "num": 8,
    "name": "Eight of Swords",
    "number": "VIII",
    "rank": "8",
    "rankLabel": "Eight",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Shortened Force",
    "meaningUpright": "You feel trapped by thoughts and beliefs rather than real walls. The restriction is self-imposed, and the way out is in sight.",
    "meaningReversed": "You are starting to see that you were never really bound. Step out of the limiting belief.",
    "keywordsUpright": [
      "feeling trapped",
      "limiting beliefs",
      "self-restriction",
      "helplessness"
    ],
    "keywordsReversed": [
      "liberation",
      "new perspective",
      "freedom",
      "taking control"
    ]
  },
  {
    "id": "swords_9",
    "num": 9,
    "name": "Nine of Swords",
    "number": "IX",
    "rank": "9",
    "rankLabel": "Nine",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Despair and Cruelty",
    "meaningUpright": "Anxiety, sleepless nights, and catastrophic thinking. Most of the fears are larger in the dark than in daylight.",
    "meaningReversed": "The nightmare is easing and you are learning to quiet your mind. Seek support and let the fears shrink.",
    "keywordsUpright": [
      "anxiety",
      "sleeplessness",
      "catastrophizing",
      "dread"
    ],
    "keywordsReversed": [
      "relief",
      "coping",
      "finding support",
      "letting fear go"
    ]
  },
  {
    "id": "swords_10",
    "num": 10,
    "name": "Ten of Swords",
    "number": "X",
    "rank": "10",
    "rankLabel": "Ten",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of Ruin",
    "meaningUpright": "Rock bottom: an ending that is painful but complete. There is nothing further to lose, and the dawn is already behind you.",
    "meaningReversed": "You are surviving the worst and beginning to recover. Stop reliving the wound and let yourself rise.",
    "keywordsUpright": [
      "rock bottom",
      "a complete ending",
      "painful truth",
      "a new dawn"
    ],
    "keywordsReversed": [
      "recovery",
      "survival",
      "the worst is over",
      "rising again"
    ]
  },
  {
    "id": "swords_page",
    "num": 11,
    "name": "Page of Swords",
    "number": "P",
    "rank": "page",
    "rankLabel": "Page",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Princess of the Rushing Winds",
    "meaningUpright": "Curiosity, sharp questions, and a hunger for truth. Stay alert, and think before you speak.",
    "meaningReversed": "Gossip, defensiveness, or words used carelessly. Let a thought settle before you broadcast it.",
    "keywordsUpright": [
      "curiosity",
      "mental agility",
      "vigilance",
      "questions"
    ],
    "keywordsReversed": [
      "gossip",
      "defensiveness",
      "careless words",
      "pettiness"
    ]
  },
  {
    "id": "swords_knight",
    "num": 12,
    "name": "Knight of Swords",
    "number": "Kn",
    "rank": "knight",
    "rankLabel": "Knight",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Lord of the Wind and Breezes",
    "meaningUpright": "Fast, direct, and certain. Charge toward the truth, but check your mirrors; speed is not accuracy.",
    "meaningReversed": "Ruthlessness, tactlessness, or arguments picked for their own sake. Certainty is not the same as being right.",
    "keywordsUpright": [
      "directness",
      "quick thinking",
      "drive",
      "candor"
    ],
    "keywordsReversed": [
      "ruthlessness",
      "tactlessness",
      "reckless argument",
      "impulsiveness"
    ]
  },
  {
    "id": "swords_queen",
    "num": 13,
    "name": "Queen of Swords",
    "number": "Q",
    "rank": "queen",
    "rankLabel": "Queen",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Queen of the Thrones of Air",
    "meaningUpright": "Clear sight and honest boundaries. Say the true thing plainly and expect the same from others.",
    "meaningReversed": "Clarity has turned cold, bitter, or cruel. The truth does not have to cut this deep.",
    "keywordsUpright": [
      "honesty",
      "clear boundaries",
      "independence",
      "insight"
    ],
    "keywordsReversed": [
      "coldness",
      "cruel sarcasm",
      "bitterness",
      "isolation"
    ]
  },
  {
    "id": "swords_king",
    "num": 14,
    "name": "King of Swords",
    "number": "K",
    "rank": "king",
    "rankLabel": "King",
    "arcana": "minor",
    "suit": "swords",
    "suitName": "Swords",
    "element": "Air",
    "ruler": null,
    "esotericTitle": "Prince of the Chariot of the Winds",
    "meaningUpright": "Authority built on logic, fairness, and discipline. Decide on the evidence and hold to your principles.",
    "meaningReversed": "Intellect used as a weapon: rigid, cynical, or tyrannical. Fairness without compassion is not fairness.",
    "keywordsUpright": [
      "intellect",
      "authority",
      "impartiality",
      "strategy"
    ],
    "keywordsReversed": [
      "cruelty",
      "tyranny",
      "rigid thinking",
      "coldness"
    ]
  },
  {
    "id": "pentacles_ace",
    "num": 1,
    "name": "Ace of Pentacles",
    "number": "A",
    "rank": "ace",
    "rankLabel": "Ace",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Root of the Powers of Earth",
    "meaningUpright": "A tangible opportunity: money, work, health, or a new foundation. Plant it where it can grow.",
    "meaningReversed": "A missed opportunity, poor planning, or a chance that looks better than it is. Read the fine print before you commit.",
    "keywordsUpright": [
      "opportunity",
      "prosperity",
      "a new foundation",
      "security"
    ],
    "keywordsReversed": [
      "a lost opportunity",
      "financial instability",
      "poor planning",
      "scarcity"
    ]
  },
  {
    "id": "pentacles_2",
    "num": 2,
    "name": "Two of Pentacles",
    "number": "II",
    "rank": "2",
    "rankLabel": "Two",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Harmonious Change",
    "meaningUpright": "You are juggling priorities and keeping it all in the air. Stay flexible, but notice what is being neglected.",
    "meaningReversed": "The juggling has become dropping; you are overextended and something is about to give. Set one thing down.",
    "keywordsUpright": [
      "adaptability",
      "balance",
      "resourcefulness",
      "flexibility"
    ],
    "keywordsReversed": [
      "overextension",
      "disorganization",
      "financial stress",
      "dropped commitments"
    ]
  },
  {
    "id": "pentacles_3",
    "num": 3,
    "name": "Three of Pentacles",
    "number": "III",
    "rank": "3",
    "rankLabel": "Three",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Material Works",
    "meaningUpright": "Skilled work and good collaboration. Your craft is valued; keep learning and keep building with others.",
    "meaningReversed": "Poor workmanship, friction on the team, or no shared plan. Agree on the approach before you continue.",
    "keywordsUpright": [
      "craftsmanship",
      "collaboration",
      "skill",
      "recognition"
    ],
    "keywordsReversed": [
      "friction",
      "shoddy work",
      "carelessness",
      "lack of skill"
    ]
  },
  {
    "id": "pentacles_4",
    "num": 4,
    "name": "Four of Pentacles",
    "number": "IV",
    "rank": "4",
    "rankLabel": "Four",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Earthly Power",
    "meaningUpright": "Holding on tight to money, control, or security. Stability is good; gripping it so hard you cannot move is not.",
    "meaningReversed": "You are loosening your grip, spending more freely, or letting go of control. Make sure it is release and not recklessness.",
    "keywordsUpright": [
      "security",
      "control",
      "saving",
      "holding on"
    ],
    "keywordsReversed": [
      "greed",
      "miserliness",
      "letting go",
      "material obsession"
    ]
  },
  {
    "id": "pentacles_5",
    "num": 5,
    "name": "Five of Pentacles",
    "number": "V",
    "rank": "5",
    "rankLabel": "Five",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Material Trouble",
    "meaningUpright": "Hardship, worry, and feeling left out in the cold. Help is closer than it looks if you will ask for it.",
    "meaningReversed": "Recovery is beginning: shelter, support, and a return to steadier ground. Accept the help.",
    "keywordsUpright": [
      "hardship",
      "isolation",
      "financial strain",
      "feeling left out"
    ],
    "keywordsReversed": [
      "shelter",
      "financial recovery",
      "rebuilding",
      "accepting help"
    ]
  },
  {
    "id": "pentacles_6",
    "num": 6,
    "name": "Six of Pentacles",
    "number": "VI",
    "rank": "6",
    "rankLabel": "Six",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Material Success",
    "meaningUpright": "Generosity flowing fairly, whether you are giving or receiving. Share without keeping score.",
    "meaningReversed": "Charity with strings attached, or a power imbalance in who gives and who owes. Check what the generosity is really buying.",
    "keywordsUpright": [
      "generosity",
      "charity",
      "fairness",
      "support"
    ],
    "keywordsReversed": [
      "strings attached",
      "power imbalance",
      "inequity",
      "debt"
    ]
  },
  {
    "id": "pentacles_7",
    "num": 7,
    "name": "Seven of Pentacles",
    "number": "VII",
    "rank": "7",
    "rankLabel": "Seven",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Success Unfulfilled",
    "meaningUpright": "You have worked hard and are waiting for the harvest. Assess what is growing and be patient with what is not ready.",
    "meaningReversed": "Impatience or disappointment with a slow return. Decide whether to keep investing or redirect your effort.",
    "keywordsUpright": [
      "patience",
      "assessment",
      "long-term effort",
      "perseverance"
    ],
    "keywordsReversed": [
      "impatience",
      "wasted effort",
      "giving up early",
      "disappointment"
    ]
  },
  {
    "id": "pentacles_8",
    "num": 8,
    "name": "Eight of Pentacles",
    "number": "VIII",
    "rank": "8",
    "rankLabel": "Eight",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Prudence",
    "meaningUpright": "Apprenticeship and craft: show up, do the work, and improve a little every day. Mastery comes through repetition.",
    "meaningReversed": "Perfectionism or tedium has drained the care out of the work. Reconnect with why you do it, or change what you do.",
    "keywordsUpright": [
      "apprenticeship",
      "craft",
      "dedication",
      "diligence"
    ],
    "keywordsReversed": [
      "perfectionism",
      "tedium",
      "cutting corners",
      "uninspired work"
    ]
  },
  {
    "id": "pentacles_9",
    "num": 9,
    "name": "Nine of Pentacles",
    "number": "IX",
    "rank": "9",
    "rankLabel": "Nine",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Material Gain",
    "meaningUpright": "Self-sufficiency and earned comfort. Enjoy the independence you built.",
    "meaningReversed": "The security looks better than it feels, or it depends on someone else more than you admit. Be honest about the numbers and about the loneliness.",
    "keywordsUpright": [
      "self-reliance",
      "comfort",
      "independence",
      "earned reward"
    ],
    "keywordsReversed": [
      "a gilded cage",
      "vanity",
      "dependence",
      "loneliness in comfort"
    ]
  },
  {
    "id": "pentacles_10",
    "num": 10,
    "name": "Ten of Pentacles",
    "number": "X",
    "rank": "10",
    "rankLabel": "Ten",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of Wealth",
    "meaningUpright": "Lasting wealth, family, and legacy. Build something that outlives the moment, or let yourself belong to what already does.",
    "meaningReversed": "Family or financial trouble, an inheritance dispute, or a tradition that has become a burden. Have the practical conversation.",
    "keywordsUpright": [
      "legacy",
      "lasting wealth",
      "family",
      "security"
    ],
    "keywordsReversed": [
      "family dispute",
      "a crumbling legacy",
      "financial burden",
      "mismanagement"
    ]
  },
  {
    "id": "pentacles_page",
    "num": 11,
    "name": "Page of Pentacles",
    "number": "P",
    "rank": "page",
    "rankLabel": "Page",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Princess of the Echoing Hills",
    "meaningUpright": "A practical beginning: studying, saving, learning a skill. Ambition here is quiet and steady.",
    "meaningReversed": "Procrastination, or plans without any practice behind them. Start the unglamorous lesson.",
    "keywordsUpright": [
      "study",
      "practical ambition",
      "eagerness to learn",
      "a first step"
    ],
    "keywordsReversed": [
      "procrastination",
      "lack of progress",
      "financial naivety",
      "wasted potential"
    ]
  },
  {
    "id": "pentacles_knight",
    "num": 12,
    "name": "Knight of Pentacles",
    "number": "Kn",
    "rank": "knight",
    "rankLabel": "Knight",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of the Wide and Fertile Land",
    "meaningUpright": "Reliable, patient, methodical progress. It is not glamorous, but it arrives on time.",
    "meaningReversed": "Stubbornness, workaholism, or a routine that has stopped leading anywhere. Change the part that is only habit.",
    "keywordsUpright": [
      "reliability",
      "endurance",
      "duty",
      "patience"
    ],
    "keywordsReversed": [
      "stubbornness",
      "workaholism",
      "tunnel vision",
      "rigidity"
    ]
  },
  {
    "id": "pentacles_queen",
    "num": 13,
    "name": "Queen of Pentacles",
    "number": "Q",
    "rank": "queen",
    "rankLabel": "Queen",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Queen of the Thrones of Earth",
    "meaningUpright": "Practical care: a home that works, money handled well, warmth you can feel. Provide it, and keep some for yourself.",
    "meaningReversed": "Caring for everyone has left you depleted, or security has become anxious control. Tend your own needs too.",
    "keywordsUpright": [
      "practical care",
      "hospitality",
      "common sense",
      "comfort"
    ],
    "keywordsReversed": [
      "self-neglect",
      "smothering",
      "status obsession",
      "anxiety about security"
    ]
  },
  {
    "id": "pentacles_king",
    "num": 14,
    "name": "King of Pentacles",
    "number": "K",
    "rank": "king",
    "rankLabel": "King",
    "arcana": "minor",
    "suit": "pentacles",
    "suitName": "Pentacles",
    "element": "Earth",
    "ruler": null,
    "esotericTitle": "Lord of the Wide and Fertile Land",
    "meaningUpright": "Steady abundance built with discipline. Share the method, not just the money.",
    "meaningReversed": "Greed, rigidity, or neglect of the material side of life. Fix the foundation before the floor gives way.",
    "keywordsUpright": [
      "abundance",
      "discipline",
      "security",
      "generosity"
    ],
    "keywordsReversed": [
      "greed",
      "stubbornness",
      "corruption",
      "neglect"
    ]
  }
];

export function getCardById(id) {
  return TAROT_DECK.find(c => c.id === id);
}

export function getCardsByArcana(arcana) {
  return TAROT_DECK.filter(c => c.arcana === arcana);
}

export function getCardsBySuit(suit) {
  return TAROT_DECK.filter(c => c.suit === suit);
}
