import type { Orientation } from "../../types";

export interface CardVoiceLines {
  upright: string;
  reversed: string;
}

/**
 * Cassian's read on every one of the 78 cards, upright and reversed.
 * The seat he finds the card in is applied separately, in positions.ts.
 */
export const INTERPRETATIONS: Record<string, CardVoiceLines> = {
  "major-0": {
    "upright": "You are in the middle of a beginning and you are trying to interview it before you agree to it. The Fool is the honest version: the step happens, and the map does not. Pack light on purpose. Accident is the method, and you keep apologizing for the method. The picture in the case is one foot already off the curb, the bag almost empty. The stake is a start you do not get to rehearse. Stamp: Put one useful thing in the bag — a key, a fare, or a name — and take the step before you design a safer one.",
    "reversed": "The leap has turned into a loop. You are calling the loop research, or caution, or bad timing. It is fear wearing a compositor's apron. The other skew is just as common: you jump so you never have to land and read what you printed. The picture in the case is a step practiced in the hallway and never taken on the street. The stake is the cost of a start you will not sign. Stamp: Choose the smaller foolishness on purpose today, and write down in one line what you refused."
  },
  "major-1": {
    "upright": "Everything required for this is already on the stone. Attention, feeling, word, and the rent. The Magician is the moment you stop lending your focus to other people's emergencies and spend it here. The miracle is concentration. The picture in the case is four tools on the bench and a hand that finally means it. The stake is the nerve to use the tools already in your hands. Stamp: Clear the bench of every other job for one hour and do the first real action with a tool you already own.",
    "reversed": "The skill is real and the aim is crooked. You are scattering the tools across other people's urgency, or polishing the presentation because the work itself scares you. Charm can print over an empty forme. Check which plate is inked. The picture in the case is a good hand performing a trick it no longer believes. The stake is talent spent on the appearance of the job. Stamp: Drop one performance today — the clever message, the extra polish — and ship the plain version."
  },
  "major-2": {
    "upright": "You know. The High Priestess will not invoice that knowledge until you stop asking the room for a second opinion. Silence here is the sound of a fact waiting for you to quit narrating it. The drawer is shut because the knowing is finished, not because it is exotic. The picture in the case is a closed drawer you already know the contents of. The stake is a knowing you keep sending out for confirmation. Stamp: Write the thing you know in one sentence and show it to nobody until morning. Then act on the sentence.",
    "reversed": "The drawer is stuck, or you are. You are drowning the signal in other people's noise, or hoarding a truth because telling it would move the furniture. Some secrets are sacred. Some are simply unpaid. You can feel which one this is. The picture in the case is a secret kept past the point where it was protecting anyone. The stake is a silence that has started charging interest. Stamp: Tell one true, unadorned sentence to the person it actually concerns. No preface."
  },
  "major-3": {
    "upright": "Something wants to grow, and it does not need your anxiety as fertilizer. The Empress is the body, the garden, the project that improves when you feed it on time and then stop hovering. Abundance here is ordinary: meals, pages, care, a thing finished enough to hold. The picture in the case is a press that keeps making more life than it was hired for. The stake is the patience to let a living thing ripen. Stamp: Tend the living part of this today — feed it, water it, or give it an hour of unpanicked attention — and then leave it alone.",
    "reversed": "Neglect has dressed up as busyness, or smothering has dressed up as love. You are not short on life. You are short on the unspectacular care that life actually eats. A creative thing sulks when you use it as a billboard. The picture in the case is a garden either starved or so fussed over it cannot breathe. The stake is care you have postponed or overdone. Stamp: Do one small bodily kindness for the work or for yourself, the kind nobody will applaud, and stop there."
  },
  "major-4": {
    "upright": "Structure is the kindness you keep treating like a cage. The Emperor sets the measure so the page can be wild inside it: a deadline, a budget, a rule you enforce on yourself before the world does. Waiting to be appointed is how the shop fills with other people's water. The picture in the case is a locked measure, and a shop that does not flood. The stake is the right to set a rule and keep it. Stamp: Write one rule for this situation, specific enough to break, and keep it for seven days.",
    "reversed": "Either the throne is empty and everything is negotiable, including your sleep, or the throne is a fist: control with no living page underneath. Look hard at which one you are calling standards. Both of them misregister a life. The picture in the case is a rule that has forgotten who it was protecting. The stake is order that has become punishment, or the lack of any order at all. Stamp: Loosen one rule that exists only to make you feel severe, or install one rule where flexibility has been an excuse."
  },
  "major-5": {
    "upright": "There is a tradition here that works. You are neither required to marry it nor to burn it for warmth. The Hierophant is the teacher, the license, the way this has been done by people who already made your mistakes. Use the key. Notice whose door you think it is required to open. The picture in the case is the house style, and the key someone put in your hand. The stake is a practice worth learning before you reinvent the bruise. Stamp: Ask the person who has actually done this for the one rule they still trust, and try it once unmodified.",
    "reversed": "You are obeying a form that no longer fits the job, or rejecting every form because one of them failed you. Both keep you from the work. Heresy is not a personality. Compliance is not a personality either. The job gets a vote. The picture in the case is a hymn book used as a lock, or a lock picked out of spite. The stake is a borrowed belief you have not tested against your own hands. Stamp: Name the rule you are following or breaking on autopilot, and decide today with the actual job in front of you."
  },
  "major-6": {
    "upright": "This is a choice, and the card is kind enough to admit the choice has a body. The Lovers is alignment: two things that can face each other without one of them editing itself down to fit. Waiting to feel sure is how you ask a decision to do an emotion's job. The picture in the case is a choice that arrived wearing a feeling's coat. The stake is a choice you cannot delegate to chemistry. Stamp: Name the two options in writing, including the one you have been pretending is not an option, and pick before the day ends.",
    "reversed": "You are out of register with your own values, or with a person you keep renegotiating yourself to keep. A half-choice is still a choice. It prints twice and looks like a ghost on the sheet. Finish it. The picture in the case is a split down a page that was meant to be one impression. The stake is the tax on a choice you will not finish making. Stamp: Stop occupying the middle. Say yes or no to the person or the path, in a full sentence, today."
  },
  "major-7": {
    "upright": "The Chariot moves because someone aims the contradiction instead of picking a favorite horse. You have the drive. Hold both pulls — speed and care, ambition and loyalty — and go anyway. Victory here is directional. The picture in the case is two horses and one pair of hands that have decided. The stake is momentum that only exists if you steer. Stamp: Point at the destination in one concrete noun, and take one distraction off the reins before noon.",
    "reversed": "Force without a road, or a road with nobody driving. You are pushing harder at a stuck thing, or you have dropped the reins and called it surrender. Spinning spends the same muscles as travel. It does not arrive. The picture in the case is horses arguing, and a wheel in a ditch you keep calling scenic. The stake is effort that is not attached to a direction. Stamp: Stop pushing for one day and fix the thing that is actually steering: the schedule, the agreement, or the goal you have not said aloud."
  },
  "major-8": {
    "upright": "The strong thing in the picture is the person who does not need to win the argument with their own appetite. Courage, patience, the soft no. You can meet the loud part of this without becoming loud. That is the craft. The picture in the case is a quiet hand on an animal that could bite. The stake is nerve that does not raise its voice. Stamp: The next time the heat rises today, lower your volume on purpose and say the firm sentence once.",
    "reversed": "Doubt has the louder mouth, or pride does. You are forcing what wants coaxing, or you are so afraid of your own force that you have gone limp. The skew is power you do not trust yourself to hold. The picture in the case is a hand either clenched in the mane or hiding in the pocket. The stake is self-trust you keep misplacing. Stamp: Do one brave thing at half volume: a boundary, an ask, or an admission, with no speech after it."
  },
  "major-9": {
    "upright": "The Hermit is the hour you take the lamp and look at the thing without an audience. You already know which room. Solitude here is a tool. You have been lending it to avoidance, or refusing it because someone might call you cold. The picture in the case is a lamp carried down a stair you stopped performing. The stake is an hour of unwatched attention. Stamp: Put the phone in the other room and spend thirty minutes alone with the actual question.",
    "reversed": "You have isolated past the point of seeing, or you are refusing the necessary quiet because the quiet would be informative. Come back far enough to speak to one person, or go far enough that the noise stops choosing for you. The picture in the case is a lamp left on in an empty shop, or a crowd used as a hiding place. The stake is solitude that has spoiled, or solitude you will not take. Stamp: If you have been alone, send one honest note. If you have been surrounded, leave the room for an hour."
  },
  "major-10": {
    "upright": "A turn is here. The Wheel does not ask permission and it does not require superstition. Something stuck is moving: timing, a season, a door. Recognize the motion and stop gripping the spoke you liked. You can ride a turn. You cannot edit one. The picture in the case is a cylinder turning while you argue with the handle. The stake is a change in luck you can meet or miss. Stamp: Say aloud what is actually turning, then take the one action that belongs to the upswing today.",
    "reversed": "Resistance has become the hobby. You are in a stalled season and calling it a personal failure, or you are forcing a repeat of luck you already spent. Fighting the downward arc makes a longer one. The picture in the case is a stuck cylinder, or a turn you are trying to drag backward. The stake is time lost arguing with a season. Stamp: Stop one effort that exists only to rewind the clock, and do the maintenance the stalled thing actually needs."
  },
  "major-11": {
    "upright": "Cause, effect, and the paperwork between them. Justice is the clean account: what you did, what was done, what the repair costs. If a decision, a contract, or an apology is due, it is due in specifics. Fairness here is a measure. The picture in the case is a blade and a scale, and no favorite customer. The stake is a consequence you have to look at straight. Stamp: Write the facts in two columns — what happened, and what you owe or are owed — and act on one line of it today.",
    "reversed": "Something is unfair, and you need to know whether the thumb is yours. You may be dodging accountability, or accepting a crooked term because arguing feels impolite. Self-blame can be as dishonest as blame. The picture in the case is a thumb on the scale, or a verdict you will not read. The stake is a crooked account you are living inside. Stamp: Correct one unfair term, yours or someone else's, in writing, with the number or the sentence attached."
  },
  "major-12": {
    "upright": "The useful move looks like doing nothing while you let the picture invert. The Hanged Man is a willing pause. You give up the angle you came in with so a different one can print. Stalling fidgets. This is still. The picture in the case is a sheet hung from a clip and seen from underneath. The stake is a pause long enough for the view to change. Stamp: Cancel one push today and look at the problem from the side you have been calling upside down.",
    "reversed": "The suspension is over, or it has rotted. You are stalling inside a pose that used to be insightful, or thrashing to get down before the lesson has finished. A pause that will not end is a refusal with better lighting. The picture in the case is a delay that has started to call itself wisdom. The stake is time spent hanging after the clip has opened. Stamp: If you have been waiting, move one inch today. If you have been thrashing, hold still for one full hour."
  },
  "major-13": {
    "upright": "An ending is on the stone. A role, a story you tell about yourself, a relationship to a plan. Death in this shop is type distributed back into the case. Mourn it if it earned mourning. Keeping it on the press is how every new sheet gets dirty. The picture in the case is a forme knocked out of the chase so another can lock. The stake is an ending you are invited to finish. Stamp: Name the thing that is over, out loud, and remove one object or habit that keeps it on the press.",
    "reversed": "You are holding a finished thing in the chase because the empty bed frightens you. The change is already here. Refusing to distribute the type does not keep the old page alive. It dirties the next one. The picture in the case is a dead forme you are still inking. The stake is grief postponed into clutter. Stamp: Put one ended thing where you cannot use it this week: the draft, the chat, the plan, the jacket by the door."
  },
  "major-14": {
    "upright": "The middle is a craft. Temperance mixes what you have been treating as enemies: speed and care, want and limit, two people who are not the same temperature. Stop lunging and measure. The ratio is the whole art. The picture in the case is two inks finding a ratio that does not muddy. The stake is a blend you have to measure. Stamp: Change one proportion today: less of what you overdo, a measured pour of what you withhold.",
    "reversed": "Excess, or a false calm. You are off the rail in a way you can feel in your sleep, or you are blending yourself into beige so nobody has to meet you. Imbalance announces itself in the body first. The picture in the case is inks dumped together, or a life so moderated it has no color. The stake is a ratio you have stopped measuring. Stamp: Correct one extreme today by a specific amount: an hour, a drink, a tone, a yes you trim."
  },
  "major-15": {
    "upright": "The chain is loose enough to lift, and you have decided it is jewelry. The Devil is the bargain you keep: the habit, the status, the joke at your own expense. It pays you in a small warmth. Name the warmth honestly, then look at the invoice. The picture in the case is a pleasant chain with a joke for a lock. The stake is a bond that pays you just enough to stay. Stamp: Name the chain without a punchline, and decline it once today where you would usually laugh and stay.",
    "reversed": "You can see the bargain. That sight is the start of the freeing, and it is unfinished. You may also be hanging the chain on someone else so you do not have to admit your hand is in it. Keep the first accusation at home. The picture in the case is a chain noticed, one link already open. The stake is a freedom that still has to be practiced. Stamp: Remove one link in the real world today: a login, a meeting, a phrase you stop offering."
  },
  "major-16": {
    "upright": "The structure comes down because a lie, a plan, or a self has been load-bearing and the load arrived. The Tower is what the strike reveals. The true parts survive. The rest was scenery. Propping it up puts you under it twice. The picture in the case is a forme locked wrong and then struck. The stake is a false structure that is already failing. Stamp: Stop repairing the thing that cracked. Clear one piece of rubble today and sleep somewhere honest.",
    "reversed": "The strike is delayed, or it already happened and you are rebuilding the same flaw with neater bricks. Fear of the collapse now costs more than the collapse. You can climb down. You do not have to wait to be pushed. The picture in the case is a crack you are painting the same color as the wall. The stake is a disaster postponed by good manners. Stamp: Admit the crack to one person who will not help you paint it, and take one brick out on purpose."
  },
  "major-17": {
    "upright": "The Star is water, night air, and the nerve to be visible while you heal. It is not a promise that nothing else will burn. You are allowed to want a future here without turning the want into a contract. Pour slowly. The well is real. The picture in the case is one clean well after the fire, and a sky that showed up anyway. The stake is a quiet hope you can actually drink. Stamp: Do one gentle, future-facing thing with your body in it: wash, walk, send the honest note, or look at the sky for a full minute.",
    "reversed": "Faith has dried into a performance, or you shut the hope because it made you feel foolish once. You are looking at the ground and calling it realism. Recover the small version of the wish, the one that does not need an audience. The picture in the case is a well you have stopped walking to. The stake is discouragement you have promoted into a personality. Stamp: Name one hope you retired too early, and give it ten unembarrassed minutes today."
  },
  "major-18": {
    "upright": "Not everything you fear is imaginary, and not everything you see in this light is there. The Moon is the unclear middle. Go slowly. Believe your unease enough to stay careful, and sign nothing the fog offers you. The picture in the case is the alley between the shop and the river, none of the dogs yours. The stake is a passage you cannot rush into clarity. Stamp: Write down what you know, what you fear, and what you invented. Sleep before you answer the third list.",
    "reversed": "Confusion is lifting, which is uncomfortable because the shapes get specific. Or you are still inside the fear and calling the fear intuition. A story that only grows at night and shrinks when you tell it to a calm person is weather. The picture in the case is a fog thinning, or a fear you have decided to obey forever. The stake is a fear that does not survive being said plainly. Stamp: Say the frightening story to one steady person in daylight, and keep only the part that is still there afterward."
  },
  "major-19": {
    "upright": "This is good, and it is simple, and you are trying to complicate it into something you can worry about correctly. The Sun is a yes, a vitality, a thing that works. Let it be warm. Success you enjoy still counts. The picture in the case is the obvious, standing in the doorway like it paid the rent. The stake is a plain good thing you might talk yourself out of. Stamp: Take the good thing at face value today and share it with someone, with no disclaimer in front of it.",
    "reversed": "Joy is delayed, or the optimism has gone so thin it has become advertising. You are dimming yourself to keep a room comfortable, or the success is real and you cannot feel it yet. Come back to something small and warm. The picture in the case is a bright day you are spending indoors with the ledger. The stake is warmth you are postponing until you deserve it. Stamp: Step into one literally brighter place today, and do the pleasurable part of the work first."
  },
  "major-20": {
    "upright": "You are being asked to answer as the person you are, not the one the old copy describes. Judgement is the reckoning that frees: forgive the earlier edition and come when called. Someone is about to tell the truth at a volume the shop can hear. It may be you. The picture in the case is a bell that calls an old name up out of the case. The stake is a calling you have already heard. Stamp: Answer the thing you have been treating as a metaphor. Make the call, submit the work, or forgive the specific person, yourself included.",
    "reversed": "Self-reproach is loud and the actual call is quiet, which is why you are listening to the wrong one. You are refusing a second chance because it would require you to stop the trial you are running against yourself. The verdict does not arrive from more evidence. The picture in the case is a bell you have decided is for other people. The stake is a refusal to answer because the old shame is familiar. Stamp: Stop one rumination mid-sentence and do the alive thing it has been substituting for."
  },
  "major-21": {
    "upright": "A cycle completes. The World is a thing that holds: the job done, the lesson in your hands, the move to a larger shop. You are allowed to arrive. Take the bow before you open a new forme just to avoid the feeling. Completion is a skill. The picture in the case is the dance at the edge of a finished sheet. The stake is an ending that is actually a fulfillment. Stamp: Mark the thing finished — send it, sign it, or celebrate it in a way your body can feel — before you start the next.",
    "reversed": "You are close, and close is the part people abandon. A loose end, or a success you will not let yourself land. Or the world you finished is already too small and you know it. One of those needs another hour. The other needs a larger page. The picture in the case is a shortcut taped across an unfinished margin. The stake is a completion you keep skipping, or a finished life you have outgrown. Stamp: Close one real loop today, all the way to the last step, or admit the loop is the wrong size and step past it."
  },
  "wands-ace": {
    "upright": "A start with heat in it. An idea, a desire, a job that woke up. The Ace of Wands is the match, not the fireplace. You do not need a five-year plan. You need to stop blowing the spark out because it arrived on an inconvenient day. The picture in the case is a live spark handed to you before you had your gloves on. The stake is a beginning that goes cold if you committee it. Stamp: Start the thing for fifteen minutes today, badly, while it is still a spark.",
    "reversed": "The urge is there and you are delaying it into ash. False starts, waiting for courage to feel like certainty, a block that is mostly a refusal to be seen beginning. Rest if you are actually empty. Fear is not rest. The picture in the case is a match struck and then argued with. The stake is heat wasted on the approach. Stamp: Make one visible mark — a sentence, a sketch, a message — and leave it where you can see it."
  },
  "wands-2": {
    "upright": "You have outgrown the first room. The Two of Wands is planning with power already in hand: the shop you know, or the larger route. Hold the map. Look. Then remember that planning is a doorway, not a room you live in. The picture in the case is a map on the imposing stone and a world past the door. The stake is a horizon you are still treating as a thought. Stamp: Choose the farther option in one concrete booking: a date, a ticket, a conversation you put on the calendar.",
    "reversed": "Fear of leaving the known room has dressed up as more research. Or you leapt with no look and the plan is now a rumor. Small is allowed. Indefinite is not. The card wants a decision about scale. The picture in the case is a map you will not hang because the door might notice. The stake is a future you keep in draft. Stamp: Commit to staying or going, in a sentence someone else can hold you to."
  },
  "wands-3": {
    "upright": "The work is in motion. You did the launching. The Three of Wands is the disciplined waiting that still counts: eyes up, room ready for what you sent out to come back larger. Do not restart the fleet out of nerves. The picture in the case is ships you already sent, and you on the dock watching the bend. The stake is expansion that needs you to stay at the dock. Stamp: Follow up once on something you already launched, then leave it alone for the day.",
    "reversed": "Delays, or a vision you never put in the water. The waiting has gone sour because there was nothing to wait for, or the return is late and you are ready to scrap the route. Check the timetable before you call it a mistake. The picture in the case is a dock with no ships, or ships you forgot you own. The stake is patience that was never earned by a launch. Stamp: Either send the thing today, or find out where the sent thing actually is."
  },
  "wands-4": {
    "upright": "A milestone, a homecoming, a table with your people at it. The Four of Wands is the pause that celebrates a foundation. Mark it. Work that is never toasted curdles into mere output. The door of this house will hold. The picture in the case is a threshold hung with the good kind of noise. The stake is a joy you are supposed to stand inside. Stamp: Mark the milestone with another person today, even if the party is two cups and an honest sentence.",
    "reversed": "The home is unsteady, or you will not let yourself arrive in it. A celebration delayed, a move that does not feel like yours, a community you are half in. Roots may be modest. They may not be hypothetical. The picture in the case is garlands taken down before the guests arrived. The stake is belonging you keep postponing. Stamp: Make one corner of your actual life more like a place you would welcome someone: a meal, a cleared table, an invitation."
  },
  "wands-5": {
    "upright": "Conflict, competition, the mess of too many wills. This is a scrum, not yet a war. Stay in the friction without deciding it means you are unsafe. Test the idea against other ideas. Notice if you are fighting for the noise. The picture in the case is five sticks in the air and nobody keeping score out loud. The stake is a clash that could sharpen you or just exhaust you. Stamp: Enter the disagreement once, on the actual point, with no extra insult and no retreat into silence.",
    "reversed": "The fight is avoiding itself. Conflict has gone indoors, or a refusal to compete is really a refusal to be seen trying. Peace that comes from nobody speaking is a paused scrum. Pick the sticks up, or set the rules down. The picture in the case is sticks lowered, either into a truce or into a sulk. The stake is friction you have driven underground. Stamp: Name the disagreement in one sentence to the person who is in it, or leave a fight that is only sport."
  },
  "wands-6": {
    "upright": "You did the thing and it is visible. The Six of Wands is public victory. Take it. Say thank you. Let the people who rode with you be seen too. Ducking the praise teaches the room to stop offering it. The picture in the case is coming back through the door with the proof in your hand. The stake is credit you are supposed to stand in. Stamp: Accept one compliment without deflecting, and name one person who helped.",
    "reversed": "Recognition is delayed, stolen, or you are chasing it so hard the work has become a costume. The card does not say you failed. It says applause is a bad compass today. Do the next piece where you can hear yourself. The picture in the case is a victory lap taken alone, or a win nobody heard. The stake is a need to be seen that has started steering. Stamp: Do the next piece of work with no announcement. If credit is genuinely missing, ask for it once, plainly."
  },
  "wands-7": {
    "upright": "You are defending a position you earned. The Seven of Wands is courage under challenge. Stay. Speak. Skip the apology for taking up the space the work requires. Make sure you are defending the work and not a mood. The picture in the case is the high ground, held longer than is elegant. The stake is ground you lose if you get polite at the wrong moment. Stamp: Hold the boundary once today without a paragraph of excuse behind it.",
    "reversed": "Exhaustion, or a siege you invented. You are outnumbered and need allies, or you are fighting every comment as if it were an army. Step down if the ground is worthless. Ask for help if it is worth it. Endless defense is neither. The picture in the case is a hill you are too tired to explain, or the wrong hill entirely. The stake is a fight that costs more than the ground. Stamp: Drop one defense that is only pride, or call in one ally for the defense that matters."
  },
  "wands-8": {
    "upright": "Speed. News, travel, a rush of motion that is actually aligned. The Eight of Wands says the arrows are loosed, so stop rewriting them in flight. Respond. Move. Clear the path. Hurry is the correct craft for once. The picture in the case is messages already in the air, none of them waiting for your edit. The stake is momentum that punishes hesitation. Stamp: Answer the oldest waiting message, and clear one obstacle from a thing already in motion.",
    "reversed": "The rush has jammed. Miscommunication, a stalled trip, too many things in the air and none of them landing. Slow down only long enough to aim. After that, waiting becomes the accident. The picture in the case is arrows scattered, a delay dressed up as one more read-through. The stake is speed lost to scatter. Stamp: Pick the one arrow that matters, send it cleanly, and leave the others on the bench."
  },
  "wands-9": {
    "upright": "You are tired and you are not done. The Nine of Wands is resilience with a bruise: one more watch, boundaries up, hope reduced to something you can carry. The wound is not a reason to abandon the post. The post is not your whole life. Rest inside the vigil. The picture in the case is a bandage, a last stand, and eyes that will not close. The stake is stamina for a finish you have already paid toward. Stamp: Protect the one thing you are guarding, and sleep anyway. Both. Tonight.",
    "reversed": "Defensiveness has outlived the battle, or you are one inch from a door you are ready to quit. Paranoia is expensive. So is abandoning a finish you can already see. Ask your body which story is true, not your pride. The picture in the case is a guard who has forgotten the shift ends. The stake is vigilance that no longer matches the danger. Stamp: Ask someone you trust whether the threat is current. Then stand down, or finish, with no extra theater."
  },
  "wands-10": {
    "upright": "The work is real and the load is foolish. The Ten of Wands is success carried like a punishment: yes after yes, until you cannot see the street. You can put some of it down. Delegation is not a moral failure. A no is not one either. The picture in the case is too many formes in your arms, all of them yours. The stake is a burden that used to be an ambition. Stamp: Set one armful down today. Transfer it, schedule its ending, or drop it.",
    "reversed": "You are refusing weight that is actually yours, or still carrying what you already agreed to release. Burnout is information. Martyrdom is a style. Choose the information and act from it. The picture in the case is a load dropped so fast something cracked, or clutched past all sense. The stake is responsibility out of scale with one pair of arms. Stamp: List what you are carrying and cross off one item that was never yours."
  },
  "wands-page": {
    "upright": "A curious spark, a message, a beginner's nerve. The Page of Wands brings the idea while it is still all elbows. Encourage it. You do not owe a masterpiece to a first knock. You owe it a door. The picture in the case is an apprentice arriving with news and a scorch mark. The stake is a beginner's excitement you might talk down. Stamp: Follow the curious impulse for one hour with no outcome attached.",
    "reversed": "All announcement, no experiment. Or a fear of looking like a beginner so complete that you never begin. Restlessness is not a path. Pick up the single stick and use it on something real. The picture in the case is a spark talked to death in the doorway. The stake is enthusiasm with no hands on it. Stamp: Stop describing the idea and make the smallest possible version of it today."
  },
  "wands-knight": {
    "upright": "Bold, fast, charming, and already halfway down the street. The Knight of Wands is a charge worth following: a trip, a campaign, a heat with a direction. Go. Take one fact with you so the fire has a road and not only a reputation. The picture in the case is motion that got promoted into a personality. The stake is courage that needs a destination. Stamp: Start the bold move today, and attach one practical detail so it is still there in the morning.",
    "reversed": "Recklessness, or a passion that keeps changing horses. You are scattering scorch marks, or so afraid of your own speed that you have stalled the knight in the yard. Aim, or rest. Revving is neither. The picture in the case is a horse in circles, heat with nowhere to go. The stake is heat spent on departure after departure. Stamp: Finish one charged thing you already started before you light the next."
  },
  "wands-queen": {
    "upright": "Warm authority. The Queen of Wands is confidence that makes other people braver: direct, visible, generous with the fire. Take up the room your work requires. Inspire by being in the work, not by managing everyone else's flame. The picture in the case is a person who can hold a room at a working heat. The stake is a presence you have been dimming. Stamp: Show the work, or the opinion, with your name on it, once today.",
    "reversed": "You are demanding the room's attention because you do not trust the work, or withdrawing your fire so nobody can criticize it. You are still the queen on a day you feel like a fraud. Three-quarter brightness is enough to enter. The picture in the case is heat turned inward: jealousy, shrinking, or a performance of confidence. The stake is confidence tangled up with being seen. Stamp: Give someone else a sincere boost, then take one square foot of credit for your own work."
  },
  "wands-king": {
    "upright": "Leadership with a long view. The King of Wands sets a direction and lets other people carry torches without grabbing them back. Decide, delegate, and stay honorable when the project gets loud. If this king is someone else, watch whether their vision leaves room for your hands. The picture in the case is vision that has learned what to do with the bellows. The stake is a direction only a leader can set. Stamp: Make the decision you have been crowdsourcing, and give the next step to a specific person, even if that person is you.",
    "reversed": "Impatience, arrogance, or a fear of leading that has you hiding behind a committee. The fire is fine. The character around it is slipping. A long view with no respect for the people in the shop is just a brighter overload. The picture in the case is a king who is all announcement, or a vision with a bully behind it. The stake is power that has forgotten it is a service. Stamp: Lead one thing quietly: decide, credit the room, and check back when you said you would."
  },
  "cups-ace": {
    "upright": "A new feeling is being offered. Love, a grief that has finally gone clean, a creative well, a yes from the body. The Ace of Cups is the open vessel. You do not have to deserve it before you hold it. You do have to stop grading it. The picture in the case is a cup offered across the counter, no speech prepared. The stake is an opening in the heart you might argue with. Stamp: Accept the feeling or the offer without putting a joke in front of it.",
    "reversed": "Emotion is blocked, or it is spilling where it was not ordered. You are repressing a tenderness because it is inconvenient, or flooding the shop with a feeling the situation did not request. Right-size it. The cup is still a cup. The picture in the case is a cup tipped, or held so carefully that nothing can be poured. The stake is a feeling you will not let arrive, or will not let be small. Stamp: Name the feeling in four words, to yourself or to the right person, and stop explaining it."
  },
  "cups-2": {
    "upright": "A meeting of equals. Partnership, friendship, mutual regard you can feel in the room. The Two of Cups is reciprocity. If it is offered, meet it. If you are in it, tell the truth at the same altitude as the other person. No pedestals. The picture in the case is two cups, level, and a pact that does not need a notary. The stake is a mutual bond that asks to be met. Stamp: Offer or answer one clear gesture of regard today, specific enough that it could be refused.",
    "reversed": "Imbalance. A break, a mismatch, a partnership where one person is composing both parts. You are idealizing someone, or refusing a real mutuality because it would cost you the upper hand. Look at the pour, not the speech. The picture in the case is two cups at different heights, a toast nobody finished. The stake is a bond out of register. Stamp: Say the unbalanced thing once, kindly and without assembling a trial, or step back from a toast you do not mean."
  },
  "cups-3": {
    "upright": "Company. The people who knew you before this particular trouble. The Three of Cups is support with laughter in it. Go be one of three, not the host of everyone. Shared joy is a structural material. Use it. The picture in the case is the third pour, friends, the toast that means you belong at the table. The stake is friendship you have been too busy to show up for. Stamp: Raise an actual glass, or its Tuesday equivalent, with someone who is on your side.",
    "reversed": "Gossip, a triangle, too much of a good night, or an isolation you are calling standards. The celebration has a rotten spot. Check whether you are excluding, excluded, or just drunk on the scene. Repair is social. So is the damage. The picture in the case is a party that left someone out, possibly you. The stake is company that has turned careless. Stamp: Repair one social thread today, or leave a gathering that only runs on someone being discussed."
  },
  "cups-4": {
    "upright": "Apathy is the lock. The Four of Cups is the sulk, the boredom, the refusal to see the next offer because the last ones disappointed you. Rest if you are truly tired. If you are merely unimpressed with your life, look up. The cup is already extended. The picture in the case is a cup offered at the edge of your vision while you study the ground. The stake is a chance you are too listless to see. Stamp: Notice one offer you have been ignoring — a message, a walk, a hand — and answer it.",
    "reversed": "The withdrawal is ending, or it has become a hole. You are ready to engage again, or you are poking at a dissatisfaction without picking anything up. Motivation returns when you lift one thing off the ground, not when a mood announces itself. The picture in the case is a person who has finally turned their head. The stake is a retreat that has done its job. Stamp: Pick up one refused opportunity and give it a fair hour."
  },
  "cups-5": {
    "upright": "Grief is in the foreground and it is legitimate. The Five of Cups does not rush you. It does point, annoyingly, at what remains. Mourn the spill at the size of the spill. Turn around before you build a house in the puddle. The picture in the case is three cups spilled, and two still standing behind you. The stake is a loss you must feel without moving into it. Stamp: Name what spilled, then name the two things still standing. Touch one of them today.",
    "reversed": "The mourning is lifting. Acceptance is available, and it can feel like disloyalty if you liked the clarity of the tragedy. You can keep a little grief and still pick up what stands. Recovery is not a verdict on how real the loss was. The picture in the case is a figure turning, at last, toward the cups that remain. The stake is a grief that is ready to share the room. Stamp: Do one ordinary pleasant thing without narrating it as a betrayal of what you lost."
  },
  "cups-6": {
    "upright": "The past offers a clean memory: childhood, a former tenderness, someone who knew you simply. The Six of Cups heals when you let it be a gift and not a country you move back to. You do not have to be young to use a little innocence. The picture in the case is an old kindness, pressed like a flower into a margin. The stake is a gentleness you remember how to do. Stamp: Give someone a small, uncomplicated kindness of the kind you once received.",
    "reversed": "You are stuck in a former room, or so defended against it that you threw out the good with the harm. Idealizing the old days and refusing to look back are both ways of not being here. Take the flower. Leave the house. The picture in the case is a past you are living in, or a past you will not let near you. The stake is memory running the press. Stamp: Keep one good old thing, and update one old story you have been telling past its accuracy."
  },
  "cups-7": {
    "upright": "Fantasy is doing overtime. Options, wishes, and fears, all in costume. The Seven of Cups is imagination without a floor. It is a beautiful way to never choose. Pick the cup that still has weight when you set it on the counter. The picture in the case is seven cups, most of them steam, one of them possibly wine. The stake is a fog of options standing in for a decision. Stamp: List the fantasies, cross out every one you cannot touch, and choose from what remains.",
    "reversed": "Illusion is failing. That is good news with a hangover. You can see the workable choice, or you are avoiding every choice because the fantasies disappointed you. Clarity is available if you will be briefly boring. The picture in the case is the steam clearing off a single real cup. The stake is a decision hiding behind daydreams. Stamp: Commit to the plain real option for one week, in writing."
  },
  "cups-8": {
    "upright": "The cups are fine and they are not enough. The Eight of Cups is the leaving: a job, a scene, a version of success that no longer touches you. You may walk toward a vaguer, truer thing. Do it cleanly. Leave the table intact on the way out. The picture in the case is a figure walking away from a full table, the moon up. The stake is a departure from something merely adequate. Stamp: Take one real step away from the thing you have emotionally already left.",
    "reversed": "You are afraid to leave, or you left and the unfinished feeling dragged you back. Drifting is not the same as a deliberate walk. Return and mean it, or go and stop touring the doorway. The picture in the case is a walker who keeps checking the table over a shoulder. The stake is a leaving you will not complete. Stamp: Decide stay or go before tonight, and tell one person which it is."
  },
  "cups-9": {
    "upright": "Satisfaction. The Nine of Cups is a wish that arrived in a form you can sit in. Enjoy it without the reflex of suspicion. Pleasure counts. Just notice the difference between contentment and a smugness that has stopped wanting anything alive. The picture in the case is the wish, sitting there comfortable, and for once correct. The stake is a satisfaction you are allowed to feel. Stamp: Take the pleasure fully for one evening, and thank the part of you that asked.",
    "reversed": "The wish disappointed, or you got it and felt nothing, or you are indulging past the point of kindness. Wanting the feeling of satisfaction is different from knowing what you want. The original wish may have been someone else's. The picture in the case is a feast ordered for a hunger it does not feed. The stake is pleasure that missed the actual hunger. Stamp: Name what you wanted underneath the wish, and give yourself one honest portion of that."
  },
  "cups-10": {
    "upright": "Emotional fulfillment of the lasting kind. Family, chosen or otherwise. A peace you do not have to keep performing. The Ten of Cups is the rainbow over an ordinary house. If you have it, protect the ordinary. If you want it, stop chasing the rainbow separately from the house. The picture in the case is cups stacked into a life that fits the people under it. The stake is a shared happiness made of ordinary days. Stamp: Invest one ordinary hour in the people who make your life feel like a place.",
    "reversed": "The picture of happiness is intact and the feeling is not. Discord at home, a value you are performing, a family story with nobody in it. Prefer a true kitchen to a perfect horizon. The card is asking for that, not mocking you. The picture in the case is a painted rainbow over a house with the lights out. The stake is harmony that has become a picture. Stamp: Have the domestic truth-telling conversation you have been replacing with a nice evening."
  },
  "cups-page": {
    "upright": "A small emotional beginning. A crush, an apology, a creative hunch, a surprising tenderness. The Page of Cups is sincere and a little ridiculous. Beginners in feeling are how adults get their lives back. Do not laugh this one off the counter. The picture in the case is a shy message from the feeling you keep sending to voicemail. The stake is a tender impulse you might mock. Stamp: Answer the small feeling with a small sincere act today.",
    "reversed": "Emotional immaturity, a creative sulk, or a message from your heart you are refusing because it sounds naive. You can be discerning without being armored. The odd little feeling is still information. The picture in the case is a page who spilled the cup and is pretending it was a trick. The stake is a feeling dismissed for not sounding clever. Stamp: Take the naive feeling seriously for one hour and see what it was asking."
  },
  "cups-knight": {
    "upright": "An invitation, romantic or artistic, delivered with feeling. The Knight of Cups means the gesture. If you are him, make the offer for real. If he is approaching, hear the offer and also look at the follow-through. Romance is welcome here. Vagueness is not required. The picture in the case is a proposal carried carefully, poetry with a horse under it. The stake is a heartfelt approach that wants an answer. Stamp: Make or answer the invitation in plain language, with a time attached.",
    "reversed": "Moodiness, jealousy, a fantasy of love with no errand attached. You are seducing a situation instead of entering it, or you are disappointed that a gesture did not rewrite your life. Ask what is actually being offered this week. The picture in the case is a beautiful approach with nothing behind the visor. The stake is charm standing in for a plan. Stamp: Translate the feeling into one practical promise and keep it, or stop offering it."
  },
  "cups-queen": {
    "upright": "Emotional intelligence of the quiet kind. The Queen of Cups listens, includes, and does not make her inner life everyone else's weather. Trust the compassion, including the portion owed to yourself. Intuition is reliable here when it is calm. The picture in the case is feeling deep enough to be still, a cup that does not spill. The stake is a depth you can hold without flooding the shop. Stamp: Listen to someone, or to yourself, for ten minutes without fixing anything.",
    "reversed": "The boundaries are wet. You are absorbing, caretaking, or so lost in feeling that you cannot see the other person clearly. Empathy without a shore becomes exhaustion, and sometimes a quiet control. Come back into your own cup. The picture in the case is a queen pouring herself out to keep the room at the right temperature. The stake is compassion with no edge. Stamp: Decline one emotional errand that was never assigned to you."
  },
  "cups-king": {
    "upright": "Mature steadiness. The King of Cups can hold love, grief, and a negotiation in the same hour without making any of them a scene. Be the calm one if you can do it without going numb. Diplomacy here is feeling plus a spine. The picture in the case is a still harbor, and a person who can feel the weather without becoming it. The stake is emotional authority that stays kind. Stamp: Handle one charged conversation at an even tone, and say the true thing anyway.",
    "reversed": "Repression, or a mood running the office. You are controlling every feeling until it leaks as manipulation, or you are so swamped you cannot be relied on. The job is not to have no weather. The job is to signal the boats honestly. The picture in the case is a harbor master either shut tight or storming. The stake is feeling either locked up or in charge of the wrong things. Stamp: Name your actual mood to the person it affects, before it runs the meeting."
  },
  "swords-ace": {
    "upright": "A truth. The Ace of Swords is the breakthrough, the clear thought, the decision that ends a muddle. It can cut a lie or a knot. Use it, and do not decorate the sentence after you have found it. Clarity is a kindness and, briefly, a shock. The picture in the case is one clean blade, edge up, cutting the fog into a sentence. The stake is a truth sharp enough to rearrange the day. Stamp: Say the clear sentence once, as short as it can be, and let it stand.",
    "reversed": "Confusion, a cruel truth, or an idea so sharp you are cutting people for the pleasure of the edge. If you cannot say it cleanly, you do not have it yet. If you can say it and you are saying it to wound, put it down. The picture in the case is a blade used on the wrong thing, or left in the drawer as confusion. The stake is thought that has lost its ethics or its point. Stamp: Rewrite the point in one fair sentence, or wait until you can."
  },
  "swords-2": {
    "upright": "A stalemate you are participating in. The Two of Swords is the refusal to look: a decision delayed in the name of peace. The peace is temporary. Take the blindfold off. You already know which blade is heavier. The picture in the case is a blindfold, two blades crossed, the tide coming in anyway. The stake is a decision being protected by not looking. Stamp: Remove one source of deliberate ignorance today, and choose.",
    "reversed": "The stalemate is breaking. You are flooded with what you refused to see, or you are stalling with a more elaborate blindfold. Too much information is the new avoidance. Decide with what you have. It is enough to cut. The picture in the case is the blindfold coming off, information rushing the shore. The stake is a stall that is out of excuses. Stamp: Set a decision time today and keep it, even if the choice is smaller than your anxiety."
  },
  "swords-3": {
    "upright": "It hurts because it happened. The Three of Swords is sorrow, separation, a sentence that landed. Do not promote it into a worldview, and do not demote it into drama. Grieve at the size of the actual cut. That is how it closes. The picture in the case is three blades and a weather system in the chest. The stake is a real hurt that wants to be named at its real size. Stamp: Name the sentence that cut, out loud, to the person who dealt it or to the empty chair.",
    "reversed": "Healing is available and you are negotiating with it, because the wound still organizes your days. Recovery will feel like losing a post you understood. You can remember the cut without keeping it polished. The picture in the case is blades loosening, the weather finally moving off. The stake is a pain you are reluctant to set down. Stamp: Stop describing the injury to anyone who enjoys the description, and give the hurt one quiet hour instead."
  },
  "swords-4": {
    "upright": "Stop. The Four of Swords is recovery, the strategic lie-down. You are not lazy. You are empty. A vigil of rest will do more for this problem than another night of thinking at it. Put the blade where you can see that you put it down. The picture in the case is the cot in the back room, the sword on the wall, rest as a tactic. The stake is rest you have been treating as optional. Stamp: Take the actual rest — horizontal, quiet, with no improvement nearby — before you plan anything else.",
    "reversed": "You are restless inside a burnout, or you have withdrawn past the point of healing. Rest that restores has an end. Rest that avoids comes with a story about why today is never the day. Check which one you are in. The picture in the case is a body getting up too soon, or a rest that turned into hiding. The stake is a pause that needs either deepening or ending. Stamp: If you are exhausted, cancel something. If you are hiding, re-enter one small obligation."
  },
  "swords-5": {
    "upright": "Somebody won and the room got worse. The Five of Swords is the hollow victory: the argument taken too far, the strategy that cost the relationship, the defeat you are still chewing. If you won like this, give something back. If you lost, skip the rematch. The picture in the case is an ugly win, two people walking away, the wind doing the commentary. The stake is a win or a loss that is poisoning the ground. Stamp: Concede one point you do not have to concede, or walk away from a fight that can only make you clever.",
    "reversed": "The desire to be right is tiring. Reconciliation is possible if you can resist a final speech. Or you are sneaking back for the swords after announcing peace. Watch your hands. Peace is a behavior, not an announcement. The picture in the case is swords being put down, a grudge losing interest in itself. The stake is conflict that is ready to end if you let it. Stamp: Make the repair without a postscript, or release the grudge in a way that changes your next action."
  },
  "swords-6": {
    "upright": "You are allowed to leave the difficult water. The Six of Swords is passage, not yet joy, already movement. Take the people who belong in the boat. Leave the argument on the shore. The new water will be quieter before it is anything else. The picture in the case is a boat leaving sharp water, the fare already paid. The stake is a necessary passage out of trouble. Stamp: Make one practical move toward the calmer side today: the form, the bag, the boundary, the ticket.",
    "reversed": "You are stuck in the departure. Unfinished business, a transition you keep postponing, a belief that you may not leave until the old shore apologizes. It will not. The fare is the leaving itself. The picture in the case is a boat tied up, the passenger still explaining the old water. The stake is a transition delayed by the wish for a cleaner exit. Stamp: Leave one unresolved piece behind on purpose, and move anyway."
  },
  "swords-7": {
    "upright": "Strategy, or sneakiness. The Seven of Swords asks what you are unwilling to do in the open. A clever independent move can be legitimate. A theft, a self-deception, or a diplomatic lie is the same picture in a worse light. If you cannot tell one ally, look again. The picture in the case is someone slipping out with an armful of blades and a plan they will not sign. The stake is a strategy that may not survive daylight. Stamp: Tell the full plan to one honest person, or drop the part you were hiding.",
    "reversed": "The deception is collapsing. Let that be a relief. Come clean. Or you are so afraid of cunning that you are refusing every necessary tactic, including ordinary privacy. Discretion is allowed. Fraud is not. You know which one you are holding. The picture in the case is a thief turning around because the blades got heavy. The stake is a secret that wants either confession or a cleaner motive. Stamp: Confess the small deception today, or own the tactic openly and proceed."
  },
  "swords-8": {
    "upright": "You are constrained, and most of the rope is an idea. The Eight of Swords is the trapped mind: shame, rumor, a story that says you cannot move. Look down. One clear step and a request for help get you out. Victimhood as an identity is the extra rope. The picture in the case is loose bindings you agreed to call a cage. The stake is a mental cage with an open gate. Stamp: Identify one bind that is only a thought, and take the physical step it forbade.",
    "reversed": "The release is underway. You are seeing the old powerlessness clearly, which can make you angry or giddy. Use it. Do not build a new cage out of the apology you think you owe for having been stuck. The picture in the case is bindings on the ground, and a person surprised to be free. The stake is a freedom you have to practice before you believe it. Stamp: Do one thing the old story said you were not allowed to do."
  },
  "swords-9": {
    "upright": "The worry is louder than the facts. The Nine of Swords is the mind at its cruelest hour: anxiety, guilt, the rehearsal of catastrophe. Some of it points at a real thing. Most of it is a blade you are holding in your own mouth. Put a light on. Tell someone. The picture in the case is three in the morning, and an inventory of everything that could fail. The stake is a night-thought that wants daylight and a witness. Stamp: Write the worry down, sleep, and in the morning keep only the line that is still a fact.",
    "reversed": "The anxiety is easing, or you are asking despair to be your personality because it feels more serious than hope. If the worry pointed at a real repair, the repair is a daytime object. Do it in the day. Live somewhere other than the rehearsal. The picture in the case is dawn on the same bed, the worst of the swords turning out to be furniture. The stake is anguish that is ready to be set on the floor. Stamp: Take one practical worry and turn it into a daytime errand. Let the rest be weather."
  },
  "swords-10": {
    "upright": "It is over. The Ten of Swords is the bottom, dramatic because bottoms are, and useful because you can stop negotiating with the thing. Stop poking the fallen plan. The dawn in the picture is small and it is not a lie. A new cycle starts after you admit the old one died. The picture in the case is an ending that has finished insisting, the sky already changing. The stake is a defeat you can stop relitigating. Stamp: Say that this specific thing is over, and do not reopen it today.",
    "reversed": "You are surviving what you thought would finish you, or you are refusing to let an ending be final because the role of the ruined person still pays. Get up. The extra swords are optional. So is the encore of the disaster. The picture in the case is a figure resisting the last inch of an ending. The stake is a rock bottom you are reluctant to leave, or to admit. Stamp: Stand up from the ended thing in one practical way: a new appointment, a deleted thread, a morning that is not about it."
  },
  "swords-page": {
    "upright": "News, vigilance, a beginner's hunger for the truth. The Page of Swords asks and watches, and sometimes talks before the facts have arrived. Use the curiosity. Leash the gossip. Ask the sharp question of the right person, not of the entire room. The picture in the case is a curious mind with a paper cut and too many questions. The stake is a hunger for truth that needs manners. Stamp: Ask one direct question you have been circling, and wait for the answer.",
    "reversed": "Scatter, spy-games, or an idea defended before it was examined. You are cynical too early, or chatty with someone else's news. The mind is quick and the ethics are late. Catch the ethics up before you send anything else. The picture in the case is a page spreading a story they only half read. The stake is words moving faster than the truth. Stamp: Retract or verify one thing you passed on before you were sure."
  },
  "swords-knight": {
    "upright": "Speed of thought, a charge toward the point. The Knight of Swords can cut a stalled mess open in an afternoon. He can also wound everyone in the lane. If you must go fast, go straight, and leave the insults in the yard. The picture in the case is an argument at full gallop, brilliant and under-braked. The stake is intellect that needs a brake, not a muzzle. Stamp: Make the direct move, and take every unnecessary sharpness out of how you do it.",
    "reversed": "Reckless words, burnout from your own speed, or a brilliant plan with no follow-through. You are attacking because stillness feels like losing, or so scattered the knight has become weather. Slow the horse. Keep the sword. The picture in the case is a charge with no thesis, only velocity. The stake is force that is not attached to a point. Stamp: Wait an hour before the next strong message you want to send. Then send half of it."
  },
  "swords-queen": {
    "upright": "The truth, delivered without padding. The Queen of Swords has boundaries, perception, and little patience for fog. You can be fair and still be warm. The warmth is in the accuracy. People trust a blade that does not pretend to be a pillow. The picture in the case is clarity with a private sorrow and a very clean edge. The stake is honest judgment you are tempted to soften into uselessness. Stamp: Give the clear assessment once, without cruelty and without a cushion of lies.",
    "reversed": "Bitterness, coldness, or a honesty so blunt it is just another way to stay untouchable. You may also be refusing your own clarity so you can stay liked. The sorrow under this card is real. It does not get to run the verdicts. The picture in the case is a private grief that has sharpened into a habit. The stake is judgment warped by pain, or by the need to be liked. Stamp: Say the true thing and one human thing in the same conversation. Skip neither."
  },
  "swords-king": {
    "upright": "Intellectual authority. The King of Swords decides from principle, evidence, and a cool head. If a ruling is needed, make it and show your work. Authority stays clean here only if someone is allowed to talk back. Invite that. The picture in the case is a ruling thought, impartial enough to be useful. The stake is a decision that has to be fair to be worth making. Stamp: Write the principle first, then the decision, and let someone competent challenge it.",
    "reversed": "Manipulation, rigidity, or the refusal of a decision you are qualified to make. The tyrant and the avoider share a fear of being wrong in public. You can hold authority without punishing people with it. You can also stop pretending you have none. The picture in the case is a mind using intelligence as a quiet tyranny. The stake is intellect separated from conscience, or from courage. Stamp: Use your judgment in the open today, and leave the other person their dignity in the same breath."
  },
  "pentacles-ace": {
    "upright": "A material beginning. Money, a body, a job, a seed. The Ace of Pentacles is tangible, and it will not stay if you only admire it. Plant it. Prosperity here starts as one solid thing, not as a vision of prosperity. The picture in the case is a coin in the palm, a real offer with weight. The stake is a concrete opportunity you have to hold onto. Stamp: Accept or plant the real offer today: the invoice, the application, the seed, the appointment.",
    "reversed": "A missed chance, a poor investment of time or money, or a scarcity panic. You are too slow with a real offer, or so rushed you cannot tell a coin from a bottle cap. Slow enough to assess. Quick enough to plant. The picture in the case is a coin set down and forgotten, or grabbed so fast it is dropped. The stake is a material start mishandled. Stamp: Review the offer with numbers, then answer yes or no today."
  },
  "pentacles-2": {
    "upright": "You are balancing more than one real obligation, and so far the dance works. The Two of Pentacles is adaptability: cash flow, time, two priorities that both deserve you. Keep the rhythm. A dance still has an end of the song. The picture in the case is two coins, and a body that has turned the juggle into a dance. The stake is a balance that needs flexibility, not more balls. Stamp: Name the two priorities in order for this week, and let something smaller drop.",
    "reversed": "Overcommitment has won, or you are pretending the juggle is fine because stopping would reveal the calendar. The mess is now expensive. Put both feet down. One thing at a time is a legitimate tempo. The picture in the case is the coins out of rhythm, a smile pasted over the drop. The stake is a balance that has become a mess. Stamp: Cancel, delegate, or reschedule one obligation before you add anything."
  },
  "pentacles-3": {
    "upright": "Craft in company. The Three of Pentacles is the bench where skill is respected: collaboration, a standard, your work taken seriously by people who know the trade. Bring your piece. Take the notes. This is a workshop, not a committee. The picture in the case is three people making one thing, and the thing getting better for it. The stake is work that gets good only if you let other hands touch it. Stamp: Ask for or offer one piece of skilled feedback, and use it in the next version.",
    "reversed": "Poor teamwork, a skill ignored, or the lone-wolf routine costing the quality. You are refusing to learn, or you are working with people who will not meet the standard. Fix the collaboration, or stop calling it one. The picture in the case is a bench where nobody will share the tools. The stake is craft blocked by ego or by the wrong partners. Stamp: Have the direct conversation about the standard, or take your piece somewhere it will actually be used."
  },
  "pentacles-4": {
    "upright": "Holding on. The Four of Pentacles can be healthy conservation: you saved, you stopped the leak. It becomes a problem when the holding is fear and the fear has your posture. Keep what is worth keeping. Release the grip that is only a disaster story. The picture in the case is a locked drawer, and a person who has forgotten the drawer is not a life. The stake is security that may have hardened into clutching. Stamp: Keep the savings. Loosen one thing you are gripping out of fear: money, credit, control, or time.",
    "reversed": "You are loosening, which is the right motion when it is chosen. Generosity, or a scatter that empties the shop. The opposite of clutching is not throwing the coins into the street. It is letting them circulate on purpose. The picture in the case is the drawer unlocked, sometimes generously and sometimes too late. The stake is a grip releasing, toward generosity or toward chaos. Stamp: Make one deliberate exchange today — spend, share, or invest — with a number attached. No leaks."
  },
  "pentacles-5": {
    "upright": "Hardship is here, in money, body, or belonging. The Five of Pentacles tells the truth about the cold and about the window you are not knocking on. Help exists. Shame is what keeps you in the snow. If you are inside the window, open it. The picture in the case is two figures in the weather, passing a lit window. The stake is a lack made worse by isolation. Stamp: Ask for the specific help, or offer it, today. Name the need in practical terms.",
    "reversed": "Recovery from a material or bodily low. The aid is working, or it is available and you are still walking past it out of habit. Endurance got you here. It does not have to be your only tool now. Come inside. The picture in the case is the door opening, the worst of the weather behind you. The stake is a hardship that is beginning to ease. Stamp: Accept the help or the appointment you have been postponing, and let one burden be shared."
  },
  "pentacles-6": {
    "upright": "Exchange. The Six of Pentacles is generosity with a standard: giving, receiving, and the power hiding in both. If you have enough, share it without a performance. If you need it, receive it without erasing yourself to pay for it. Look at who holds the scale. The picture in the case is a measured giving, scales in one hand and coins in the other. The stake is a flow of resources that ought to be fair. Stamp: Give or receive one specific thing today, and notice whether the terms are clean.",
    "reversed": "Charity as control, debt as an identity, or a refusal to be in the economy of care. You are giving in order to be owed, or refusing help in order to stay imaginary-independent. Take the strings off, or do not give. The picture in the case is strings on the gift, or a hand that will not open in either direction. The stake is generosity tangled up with power. Stamp: Remove one string from what you give, or accept one gift without paying it back immediately."
  },
  "pentacles-7": {
    "upright": "You planted. The Seven of Pentacles is the long look: is this growing the way the work deserved? Patience is correct. So is an honest count. Do not pull the plant up. Do not worship it. Decide what the next season needs. The picture in the case is a pause at the vine, assessing what the season actually did. The stake is a long effort that deserves a clear-eyed review. Stamp: Review one investment of time or money, and decide whether to continue, adjust, or stop.",
    "reversed": "You are quitting before the fruit out of restlessness, or persisting in a field that has already told you the truth. Sunk cost is not a crop. Look at the actual plant, not at how hard you worked beside it. The picture in the case is impatience at the vine, or a poor harvest you will not admit. The stake is effort continued or abandoned for the wrong reason. Stamp: Measure the result in facts. Then keep the work or leave it, with no speech about how hard it was."
  },
  "pentacles-8": {
    "upright": "Apprenticeship. The Eight of Pentacles is the honest hour: show up, do the piece, do the next piece. Skill arrives as a side effect of attention. This is not a shortcut. It is how you become someone whose work can be trusted. The picture in the case is the bench, the repetition, the craft getting into the hands. The stake is mastery that only comes from the next honest repetition. Stamp: Sit at the bench and improve one detail of the work, with no audience.",
    "reversed": "Tedium has curdled the craft. You are cutting corners, or polishing one coin forever so you never have to show the set. Quality is care plus completion. Return to the bench, or change benches. Do not haunt it. The picture in the case is a sloppy bench, or a perfection that never lets a piece leave. The stake is work done without attention, or attention that will not finish. Stamp: Finish one piece at a good standard today, or redo the corner you know you skipped."
  },
  "pentacles-9": {
    "upright": "Self-sufficiency with some beauty in it. The Nine of Pentacles is earned leisure: your own money, your own taste, your own gate. Enjoy the garden. Solitude you paid for with skill does not require an apology. Invite someone only if you want them. The picture in the case is a garden grown on purpose, and the quiet of standing in it. The stake is an independence you get to inhabit. Stamp: Spend one unhurried hour in a pleasure you earned, and produce nothing during it.",
    "reversed": "The independence is shakier than it looks, or you have built a lovely life you will not let yourself enjoy. Be honest about the numbers, or about the loneliness. Then take one step toward enough. The picture in the case is a garden tended for show, or a dependence you will not name. The stake is security that is either fragile or joyless. Stamp: Look at the actual numbers or the actual loneliness, and change one thing about it today."
  },
  "pentacles-10": {
    "upright": "Legacy. The Ten of Pentacles is wealth that outlasts a mood: family, a business, a tradition, the material end of a long effort. Contribute to it, or let yourself belong to it. The card likes a meal, a repair, a paper that still matters later. The picture in the case is a house, a long work made visible, people in the yard. The stake is a lasting structure worth building or joining. Stamp: Do one thing that benefits the household or the long work: the paperwork, the gathering, the repair.",
    "reversed": "Trouble in money or family, a tradition that has become a trap, instability where you wanted a house. The picture is failing in a specific place. Find that place. Short-term thinking is how these houses fail. So is obeying a legacy that harms the people in it. The picture in the case is a family fortune with a crack in the wall. The stake is a long structure that needs repair or release. Stamp: Have the practical conversation about money, home, or family, with the documents nearby."
  },
  "pentacles-page": {
    "upright": "A practical beginning. The Page of Pentacles studies, saves, and takes the first tangible step toward a skill. Ambition here is quiet and physical. There is no humiliation in being new when your hands are already in the work. The picture in the case is a student holding one coin as if it were a seed, because it is. The stake is a practical ambition at the very start. Stamp: Enroll, budget, or practice the first lesson today. One session.",
    "reversed": "Procrastination, a stalled plan, or an appetite for the result without the study. You may be so afraid of looking like a beginner that you will not pick up the coin. The page does not get dignified first. The page gets to work. The picture in the case is a student who keeps announcing the course and missing it. The stake is a goal with no practice under it. Stamp: Do the unglamorous lesson for thirty minutes. Tell no one."
  },
  "pentacles-knight": {
    "upright": "Patience, duty, the routine that delivers. The Knight of Pentacles is not glamorous and does not care. He is the one who arrives with the work done. Be thorough. Be on time. Let other people keep the fireworks. The picture in the case is slow reliable progress, a horse that knows the road. The stake is reliability as the whole method. Stamp: Do the next dutiful step on the long task, carefully, and stop for the day when it is done.",
    "reversed": "Stuck, or plowing a routine that no longer leads anywhere useful. Perseverance is not the same thing as inertia. If the road is right, your boredom is not a verdict. If the road is wrong, duty is just a costume. The picture in the case is a knight so still he has become a milestone, or so stubborn he missed the turn. The stake is routine either abandoned or obeyed past its sense. Stamp: Keep the useful routine, and change the one part of it that is only habit."
  },
  "pentacles-queen": {
    "upright": "Practical nurture. The Queen of Pentacles makes a place where people and work can eat. Home, money handled with care, competence you can feel. Comfort is one of the tools. Provide it, and keep the account book open beside it. The picture in the case is the body of a business, generous and exact, a garden beside a ledger. The stake is care that shows up as something solid. Stamp: Make one material thing better for a living creature today, yourself included: the meal, the bill, the room.",
    "reversed": "Work has swallowed the body, or the caretaking has, or the focus on security has gone tight and anxious. You may be furnishing everyone else's comfort and skipping your own. A depleted queen helps nobody well. Come back to the senses. The picture in the case is a queen neglecting the house, or trapped inside it. The stake is practical care that has left someone out, often you. Stamp: Restore one bodily or domestic basic you have been skipping, and let another adult carry one chore."
  },
  "pentacles-king": {
    "upright": "The provider who arrived. The King of Pentacles is abundance with discipline: a steady hand, generous because the foundation is real. Share the method, not only the coins. If you are dealing with him, notice whether his security leaves other people smaller. The picture in the case is mastery of the material, security treated as a craft. The stake is long-term stability, and the character required to hold it. Stamp: Make one decision that favors the long foundation over the quick win, and be generous on the way.",
    "reversed": "Stubbornness about money, status used as a wall, or a neglect of material life dressed up as being above it. The failure here is a rich shop with a rotten floor, or a refusal to learn the business of your own life. Both can be repaired. The picture in the case is a king greedy with the house, or careless of the floor. The stake is security corrupted by greed, rigidity, or neglect. Stamp: Fix one practical foundation — a bill, a habit, a promise about money — without a speech about how busy you are."
  }
};

export function getCardLine(cardKey: string, orientation: Orientation): string {
  const entry = INTERPRETATIONS[cardKey];
  if (!entry) {
    throw new Error(`Cassian does not keep a card called "${cardKey}" in the case.`);
  }
  return entry[orientation];
}
